### ISSUE TITLE
UIDL Component definition refactoring to address #87 and #35

### ISSUE THREAD

**Issue by vladnicula** [teleporthq/teleport-code-generators#105]
Related issues #35 and #87

# Summary

In order to use dynamic data like props and local state in a way that allows us to expand the functionality and support more use cases (#35) we need to switch from the string representation approach to a JSON based structure. In a similar way, this structure should also support a new type of property assignment called assets (#87).

This ticket is for a discussion / proposal for the UIDL representation of the entire component as the changes that were applied to `children` (defined [here](https://github.com/teleporthq/teleport-code-generators/blob/master/src/uidl-definitions/schemas/component.json#L140), example [here](https://github.com/teleporthq/teleport-code-generators/blob/master/examples/uidl-samples/component-author-card.json)) 

# Motivation

Why are we doing this? What use cases does it support? What is the expected
outcome?

I'm proposing this because the changes to the way we use props affect not just attributes and style props of a component, but affect much more. Children in particular are a challenge as the ways we attempted to distinguish between what type of assignment was by checking for a `type` key in the objects like so:

```js
// old Component content
{
    children: ["$props.children"]
}
```

First attempt was to use a property assignment as suggested in #87 

```js
// new Component content
{
    children: [{
         type:"prop",
         content: { ref: "children" } 
     }]
}
```

How do we write exceptions for props, state, local, assets and so on when treating a type of a child component?

```js
{
    children: [{
         type:"NotSure",
         style: {}
     }]
}
```

This kind of representation created a conflict with the way the `type` key was used. The `type` key is used in children and in the `content` key on components to declare **what type of UI node we are going to use when rendering that content**. 

This changes with the addition of dynamic parameters as json. No longer are `type` keys just for names of nodes to be used in this component. 

# Detailed design

In order to accommodate both **nodes** and **params** we defined the idea of UIDLChild in the children array, which has a generic `type` and contains different kinds of content based on the type.

```ts
interface UIDLAbstractChild<T> {
  type: string
  content: T
}
```

Each type of content we found in the examples and tests was given an interface. The normal node content received the old content and the type `node`. Static strings that were supposed to become just plain text became `static`.

We found out that states and repeaters were also used as children. So we introduced them too. The definition worked fine as from this moment forward children were always like this:

```js
{ children: [{type: a, content: ...}, {type: b, content: ...} ... ] }
```
This worked fine until attempting to integrate the children representation into the main component definition. 

For reference, the [ComponentUIDL interface]( https://github.com/teleporthq/teleport-code-generators/blob/master/src/typings/generators.d.ts#L55) was updated a little bit from:

```js
interface ContentNode {
  type: string
  name?: string
  key?: string // internal usage
  states?: StateBranch[]
  repeat?: RepeatDefinition
  dependency?: ComponentDependency
  style?: StyleDefinitions
  attrs?: Record<string, any>
  events?: EventDefinitions
  children?: Array<ContentNode | string>
}
```

TO:

```
interface UIDLContentNode {
  type: string
  name?: string
  key?: string // internal usage
  dependency?: ComponentDependency
  style?: StyleDefinitions
  attrs?: Record<string, any>
  events?: EventDefinitions
  children?: UIDLChild[]
}

```
However this is not enough. The new `UIDLContentNode` assumes that we have a type which is a component type. It cannot support states or repeaters on the root element. We however use the states on the root components that we use in project generators to make the pages. 

# Required clarifications

- Could we introduce the same clear `type` key for the main content area of the component? 

```
interface ComponentUIDL {
  $schema?: string
  name: string
  content: UIDLContentNode
  meta?: Record<string, any>
  propDefinitions?: Record<string, PropDefinition>
  stateDefinitions?: Record<string, StateDefinition>
  assetDefinitions?: Record<string, AssetDefinition>
}
```

would become:

```
interface ComponentUIDL {
  $schema?: string
  name: string
  content: UIDLChild
  meta?: Record<string, any>
  propDefinitions?: Record<string, PropDefinition>
  stateDefinitions?: Record<string, StateDefinition>
  assetDefinitions?: Record<string, AssetDefinition>
}
```

- What are the implications for states and repeaters that are used[ like this route definition](https://github.com/teleporthq/teleport-code-generators/blob/master/examples/uidl-samples/project-state-components.json#L94)

**Comment by vladnicula** [comment]
```ts
interface UIDLComponent {
  $schema?: string
  name: string

  // content: UIDLChild which is basically:
  content: {
    type: "node" | "state" | "repeat" | "static" | "dynamic",
    content: "depending on type"
  }

  // jack of all trades 
  meta?: Record<string, any>
  
  // various props, state, assets and more
  propDefinitions?: Record<string, PropDefinition>
  stateDefinitions?: Record<string, StateDefinition>
  assetDefinitions?: Record<string, AssetDefinition>
}
```

<img width="875" alt="Screenshot 2019-03-28 at 10 06 02" src="https://user-images.githubusercontent.com/126038/55140716-71792680-5141-11e9-9e63-0fef079caa4d.png">

**Comment by alexnm** [comment]
based on the original proposal and the discussions we had at the end of the last week, here's one version of the UIDL which might include all the proposed changes:

```
{
  name: 'New UIDL',
  propDefinitions: {
    title: {
      type: 'string',
      defaultValue: 'Hello',
    },
    items: {
      type: 'array',
      defaultValue: [],
    },
  },
  instance: {
    type: 'element',
    content: {
      element: 'container',
      attrs: {
        'data-static-attr': {
          type: 'static',
          content: 'test',
        },
        'data-dynamic-attr': {
          type: 'dynamic',
          content: {
            referenceType: 'prop',
            id: 'title',
          },
        },
      },
      children: [
        {
          type: 'element',
          content: {
            element: 'text',
            children: [
              {
                type: 'static',
                content: 'Hello World!',
              },
              {
                type: 'dynamic',
                content: {
                  referenceType: 'prop',
                  id: 'title',
                },
              },
            ],
          },
        },
        {
          type: 'repeat',
          content: {
            node: {
              type: 'element',
              content: {
                element: 'text',
                children: [
                  {
                    type: 'dynamic',
                    content: {
                      referenceType: 'local',
                      id: 'item',
                    },
                  },
                ],
              },
            },
            dataSource: {
              type: 'dynamic',
              content: {
                referenceType: 'prop',
                id: 'items',
              },
            },
            meta: {
              useIndex: true,
              iteratorName: 'item',
            },
          },
        },
      ],
    },
  },
}
```
