### ISSUE TITLE
Support non-scalar values in props/state/local

### ISSUE THREAD

**Issue by alexnm** [teleporthq/teleport-code-generators#112]
We have little support for arrays at the moment (props/local) and no support for objects. As we're moving towards a more flexible structure in the UIDL, we should make sure we have (even if limited for the beginning) support for accessing complex structures via `props` and `state`

**Comment by vladnicula** [comment]
Assigning an array of declared entities is also not that great right now. We should spec array assignments a bit better too.

**Comment by vladnicula** [comment]
@alexnm how about:

```js
 {
  someStyleValue: {
    "type": "dynamic",
     "content": {
        "referenceType": "prop",
        "id": "layout.header.direction"
     }
  }
}
```

**Comment by vladnicula** [comment]
or we could have something else instead of id. Path maybe? 

```
{
        "referenceType": "prop",
        "path": "layout.header.direction"
}
```

```
{
        "referenceType": "prop",
        "referencePath": "layout.header.direction",
        "referenceBehavior": "assign"
}
```

and one step further, take the value of `props.options.getInjectedData()` and put in as props here:

```
{
        "referenceType": "prop",
        "referencePath": "options.getInjectedData",
        "referenceBehavior": "functionCall"
}
```

**Comment by alexnm** [comment]
dot notation looks good, interesting idea with the `referenceBehavior`, can be a nice abstraction for working with event handlers

**Comment by vladnicula** [comment]
We now have support for `props.someMap.someValue`
