### ISSUE TITLE
Revisit PropTypes handling

### ISSUE THREAD

**Issue by alexnm** [teleporthq/teleport-code-generators#12]
PropTypes are not too flexible at the moment
- [ ] each prop requires a default value to be displayed
- [x] we don't have the ability to set more complex default values (ex: object, array)
- [x] children props don't have a clear definition/standard (also check slots in vue)

**Comment by vladnicula** [comment]
I think we should move this out of the Beta 0.5/0.6 release. We wont take care of it till then.

**Comment by JayaKrishnaNamburu** [comment]
And how about we start supporting OneOfType to make it more flexible like ability to map one or more values, I can't currently come up with a specific use case for this, but as we might have a discussion on this, i thought if we will to support in future the UIDL must go a little change if i am not wrong and in 0.6 as UIDL is undergoing some change, just mentioning.
~~~
TimeSince.propTypes = {
  time: PropTypes.oneOfType([
    PropTypes.number,
    PropTypes.instanceOf(Date)
  ])
}
~~~

**Comment by alexnm** [comment]
not sure if we want to support too much inconsistency in terms of props, but fair point

**Comment by JayaKrishnaNamburu** [comment]
Yes it opens gates for lot of possible inconsistencies, lets see what @vladnicula and others have to say about this and i am not sure about this support for Vue, will check that 👍

**Comment by JayaKrishnaNamburu** [comment]
Hey @alexnm i think we currently support objects for the prop-types right? Here is an example that i generated from master.

~~~
const ComponentWithAttrProp = (props) => {
  return (
    <div
      style={{
        flexDirection: props.direction,
        height: props.config.height,
        alignSelf: 'center',
      }}
    />
  )
}

ComponentWithAttrProp.defaultProps = {
  direction: 'row',
  config: {
    height: 32,
  },
}

ComponentWithAttrProp.propTypes = {
  direction: PropTypes.string,
  config: PropTypes.object,
}
~~~

**Comment by JayaKrishnaNamburu** [comment]
And are we not going to make the requirement for ``defaultValue`` to be mandatory?

**Comment by alexnm** [comment]
This should work, but it's not 100% safe at this point. simply saying that the prop is of type `object` doesn't tell you anything about its shape. but it should work for now.

Not sure about the default value, I think it's debatable at this point. Also, there's the point of making some prop `required`, which is again translated into something else in React/Vue

**Comment by alexnm** [comment]
close by accident because of #219. we should think about the default / required thing before moving further

**Comment by JayaKrishnaNamburu** [comment]
for ``required`` i have something like this, How about we add a additational flag to the UIDL as ``isRequired``. So, the UIDL will look something like this

~~~
"name": {
  "type": "string",
  "defaultValue": "Hello",
  "isRequired": true / false
}
~~~

In ``PropTypes`` generation we can use this to add it to the expression.

**Comment by alexnm** [comment]
I like the idea, however, this requires changes in both the React Proptypes and the Vue Base plugins

**Comment by JayaKrishnaNamburu** [comment]
I will give it a try and implement this then 👍
