### ISSUE TITLE
';' crawled inside the vue-basic project exporters

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [teleporthq/teleport-code-generators#123]
I was exporting a few Vue basic projects and found out that ``;`` got crawled inside the template and our exported projects are having ``;`` in them.

Here is the file --> https://github.com/teleporthq/teleport-code-generators/blob/master/examples/project-exporters/vue-basic/project-template/src/App.vue#L1

~~~
;<template>
  <router-view />
</template>
~~~

**Comment by JayaKrishnaNamburu** [comment]
The behavior is strange, even if I make a change and try to commit it, at the time of commit stage the ``;`` is being added to the file, is it something intentional behavior which I miss took? 😅

**Comment by vladnicula** [comment]
Does this break the Vue component?

**Comment by JayaKrishnaNamburu** [comment]
No @vladnicula currently it is not breaking the project execution, but this ``;`` is being generated only in commit phase.

**Comment by ovidiuionut94** [comment]
This behavior is intended by prettier, when `--no-semi` flag is used.
https://prettier.io/docs/en/rationale.html#semicolons

In order to fix this, all the project templates were added in the `.prettierignore` file
