### ISSUE TITLE
Self Closing tags for Vue templates with empty children

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [teleporthq/teleport-code-generators#126]
With the new HAST to util package which we are using, currently instead of generating self-closing tags usual HTML tags are being generated.

## Current Behaviour
~~~
      <h3>{{authorName}}</h3>
      <div>
        Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae      
       </div>
      <div></div>
~~~

## Expected Behaviour
~~~
      <h3>{{authorName}}</h3>
      <div>
        Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae      
     </div>
      <div />
~~~

**Comment by JayaKrishnaNamburu** [comment]
Hi @alexnm this is currently an issue that is going on in the package itself, you can find it here --> https://github.com/Prettyhtml/prettyhtml/issues/106 once the issue is resolved, I will update our dependency and resolve this 👍

**Comment by JayaKrishnaNamburu** [comment]
So, after the discussion on the thread, the repo currently supports for elements that are published under [html-void-elements](https://www.npmjs.com/package/html-void-elements)

**Comment by alexnm** [comment]
as long as tags like img and input are properly self-closed, we are fine with the current implementation imo. let's reopen this later if needed
