### ISSUE TITLE
Support for accessing props using $props.toggle in 0.5

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [teleporthq/teleport-code-generators#128]
Hi, currently i assume we are supporting the following convention ``$props.toggle`` for accessing props in our UIDL Schema. So here is the strange behaviour from the ``createReactComponentGenerators`` from the current master

## UIDL Used
~~~
{
    "$schema": "https://raw.githubusercontent.com/teleporthq/teleport-code-generators/master/src/uidl-definitions/schemas/component.json",
    "name": "SimpleToggleComponent",
    "stateDefinitions": {
      "toggleComponent": {
        "type": "boolean",
        "defaultValue": false
      },
      "toggleTab": {
        "type": "number",
        "defaultValue": 0
      }
    },
    "content": {
      "type": "container",
      "children": [
        {
          "type": "text",
          "name": "input-box",
          "events": {
            "onClick": [
              {
                "type": "stateChange",
                "modifies": "toggleComponent",
                "newState": true
              }
            ]
          }
        },
        {
          "type": "state",
          "name": "toggleComponent",
          "states": [
            {
              "value": true,
              "content": {
                "type": "text",
                "children": ["The State of the component is true"]
              }
            },
            {
              "value": false,
              "content": "This is second"
            }
          ]
        },
        {
          "type": "state",
          "name": "toggleTab",
          "states": [
            {
              "value": "$props.toggleComponent",
              "content": "The state is on tab 1"
            },
            {
              "value": 1,
              "content": "The state is on tab 2"
            }
          ]
        }
      ]
    }
  }
  
~~~

When we are running ``createVueComponentGenerator`` on the same UIDL i am able to generate the Vue Component. But the same Schema throws the following error for react
```
The plugin reactStyledJSXChunkPlugin failed. Process continues. Moving forward to the next plugin. TypeError: Property value exp
ected type of number but got string
    at Object.validate (teleport-code-generators/node_modules/@babel/types/lib/definitions/ut
ils.js:161:13)
```

The error is occurring in our Assembly Line exactly here --> https://github.com/teleporthq/teleport-code-generators/blob/master/src/core/assembly-line/index.ts#L25

### Improvements that be helpful for the User Experience
- Currently the error says ``Property value expected type of number but got string`` but it takes a lot of time to figure out where exactly and which value in the ``schema`` is responsible for this, it would be so great if we can throw the ``attribute_name`` where the error occurred while modifying.
- If a Plugin is failing the consequent plugins are failing resulting in the pipeline to stop

**Comment by alexnm** [comment]
your error is coming from here:

```"value": "$props.toggleComponent"```

value should be an exact value of the state key `toggleComponent`, so either `true` or `false`.
you should also change the value below from `1` to `true` or `false`

better doc for handling state changes will come after `v0.6`

**Comment by JayaKrishnaNamburu** [comment]
> your error is coming from here:
> 
> `"value": "$props.toggleComponent"`
> 
> value should be an exact value of the state key `toggleComponent`, so either `true` or `false`.
> you should also change the value below from `1` to `true` or `false`
> 
> better doc for handling state changes will come after `v0.6`

Yup got that, what i mean't was with the same UIDL, vue-generators are working normally but react are failing, if it is the intended behaviour we should cross check the validations happening in vue generators 👍

**Comment by alexnm** [comment]
ASTs are more typesafe and fail whenever something is wrong. for Vue, there's a lot of string generation and normally that doesn't fail at generation time :)

**Comment by alexnm** [comment]
@JayaKrishnaNamburu can we close this?

**Comment by JayaKrishnaNamburu** [comment]
Yeah, i think we can close this as the PR is also merged 👍
