### ISSUE TITLE
Support for slots

### ISSUE THREAD

**Issue by alexnm** [teleporthq/teleport-code-generators#156]
Originally we were supporting the concept of `props.children` from React, but we believe that slots are a bit closer to the web components standard.

With the new UIDL structure, we will be able to write something like this:

```{ "type": "dynamic", "content": { "referenceType": "slot", "id": "default" }```

This will be translated into

```{ props.children }``` in React
```<slot></slot>``` in Vue

**Comment by vladnicula** [comment]
Why not `{ "type": "slot", "content": "default" }` ?
