### ISSUE TITLE
Reducing the package size of our npm package

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [teleporthq/teleport-code-generators#159]
## Improvements 🚀 

Hello, so as a front end developer i always like to make my bundls less in size so i can cheat on compile and parse times of the bundle. So today when i am trying to download our package from **npm** i observed we are packing few things that are actually not needed for the end users to use in their projects, here are few of my observations.

1. We are exposing our entry point as **dist/index.js** but still we are packing our src too in the pack.
2. We are packing our ``uidl-samples`` which were actually in-accessible when we install teleport as a dependency in any other project.
3. This is also taking a sum of nearly ``103kb`` in the package, we have a ``png`` image of the ``teleporthq`` logo. (Here is an awesome [article](https://medium.com/s/silicon-satire/i-peeked-into-my-node-modules-directory-and-you-wont-believe-what-happened-next-b89f63d21558) that talk about this)

I made few changes and added ``.npmignore`` and generated a package with the new changes and the ``gzip`` size is **103kb** now.

Here are the [files](https://drive.google.com/drive/folders/1xD2xA9V7B_ltqJGJ6O_t2H7y8FsYbugb?usp=sharing), one is from the npm and the other is locally generated, and here is how to test it. After downloading the file, move it to the folder where you want to install and then yu can directly run ``npm install <file-name>``

This is how your ``package.json`` will look
~~~
"@teleporthq/teleport-code-generators": "file:teleporthq-teleport-code-generators-0.5.1.tgz"
~~~

Please try this and let me know your views and suggestions, we can bring the size from **298kb** to **103kb**  

# 🔥

**Comment by vladnicula** [comment]
I think we discussed about removing the SRC folder form dist package. Good idea. :) 

We were going to address the package size after we started to split the mono repo into multiple npm packages but this is a nice starting point.

**Comment by alexnm** [comment]
@JayaKrishnaNamburu is this still relevant after the lerna setup?

**Comment by JayaKrishnaNamburu** [comment]
Tomorrow I will update all packages with ``.npmignore``or update the files that are actually needed for packing in ``package.json`` and then I will close this @alexnm. let us open this until that task is completed

**Comment by alexnm** [comment]
@JayaKrishnaNamburu any updates on this one? I'd like us to clean up remaining tickets which are not impacting the next releases

**Comment by JayaKrishnaNamburu** [comment]
Yeah we can close this now.
