### ISSUE TITLE
Style and media queries representation

### ISSUE THREAD

**Issue by vladnicula** [teleporthq/teleport-code-generators#166]
We currently have an exclusive node type used only for the situation of media queries. They are called `nested-styles` and have been created only for this purpose. 

Rather than having this node type, I suggest we consider defining the media query selectors as part of the style definition. 

What I mean by it is this:

```
style: {
   "*" : {
       // non media query specific styles here 
    },
   "@media(something something tablet)": {
      // media query specific styles here
    },
   "@media(something something mobile)": {
      // media query specific styles here
    }
}

This way we have a simpler way of dealing with media queries, and looking at packages like https://www.npmjs.com/package/react-native-media-queries I think we'll be safe with such an approach for react native as well.

**Comment by alexnm** [comment]
this could work better than mixing media queries with styles, but we should also have the option to pass regular styles without defining the `"*": {...}` key always

**Comment by alexnm** [comment]
I would bring this into discussion some time soon, before going with the official release

**Comment by vladnicula** [comment]
Closing this in favour of https://github.com/teleporthq/teleport-code-generators/issues/337
