### ISSUE TITLE
Showcase project generators in codesandbox using xhr-based sandbox generation

### ISSUE THREAD

**Issue by vladnicula** [teleporthq/teleport-code-generators#168]
Our examples and / or docs could use the [XHR Based Generation of CodeSandbox projects](https://codesandbox.io/docs/importing#xhr-request) to generate code sandboxes on the fly for given UIDLs. 

This could be great for testing out project generators and showing examples on the fly. 

Coincidently, the codesandbox api matches the project generator output quite well. 

<img width="368" alt="Screenshot 2019-04-09 at 16 07 52" src="https://user-images.githubusercontent.com/126038/55802808-a7bf8a00-5ae1-11e9-821a-b58cae010552.png">

**Comment by JayaKrishnaNamburu** [comment]
That will an awesome feature @vladnicula ✨

**Comment by vladnicula** [comment]
We'll probably look at this two week from now or so :)

**Comment by JayaKrishnaNamburu** [comment]
I think we can you this for our component generators --> https://github.com/codesandbox/codesandboxer

**Comment by alexnm** [comment]
closing this as we'll resume the discussion on the codesandbox integration and the work will happen most likely in #326
