### ISSUE TITLE
Template formatting for .vue files

### ISSUE THREAD

**Issue by alexnm** [teleporthq/teleport-code-generators#17]
The XML built template chunk of the vue file is not properly formatted. We should look into the prettier formatting plugins or find a different solution.

**Comment by paulbrie** [comment]
Besides the indentation, I also have found an extra first empty line which should not be here.

![image](https://user-images.githubusercontent.com/3997538/53580833-1f1a0980-3b85-11e9-892b-06f6d1b6f2fd.png)

**Comment by alexnm** [comment]
formatting html requires `htmlWhitespaceSensitivity`: `ignore` to work as expected in a .vue component
