### ISSUE TITLE
Proposal to adopt type script style of Error Format

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [teleporthq/teleport-code-generators#174]
## Proposal

Hi today when I was trying to fix a bug, I took a couple of minutes to figure out actually in which phase the error is occurring, like for example Builder, Resolver or Plugins. Then I was wondering if we can adopt the typescript style of errors like ``TS2300`` [link](https://github.com/aurelia/skeleton-navigation/issues/779)

The error which we are manually throwing can have a prefix like
~~~
[location-code] <Actualy Error Message>
~~~

Roughly something like this
~~~
[TG-VL] --> for validators
[TG-RS] --> for Resolvers
[TG-RB] --> for React base component
~~~

Upsides
- Easy to Document all the errors, like a single knowledge base.
- We can find the error location immediately, just by looking at the error message.

What are your views on this ? is the naming convention really worth the hard work, I am not sure, just a rough idea 🤔  .

**Comment by alexnm** [comment]
I like the idea of structure, we have to look into this, let's open the discussion soon

**Comment by JayaKrishnaNamburu** [comment]
Hey guys any thoughts on this, since the packages are split now. I think it will be greatly helpful if we take a call on this

**Comment by alexnm** [comment]
let's discuss during this week

**Comment by alexnm** [comment]
@JayaKrishnaNamburu would you like to continue expanding on this proposal?

**Comment by JayaKrishnaNamburu** [comment]
I felt it is a good thing to add to the system. But now I fell we don't need it as we decoupled into multiple packages and we can easily find out where the bug is creating the issue.

**Comment by alexnm** [comment]
ok, closing it for now, as we have other priorities
