### ISSUE TITLE
Component names are not same as specified in UIDL

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [teleporthq/teleport-code-generators#175]
After this #168, I tried exporting a project from CLI too code sandbox using ``codesandbox cli`` and a sandbox is created here --> https://codesandbox.io/s/8zz2kr8118 and then here is the bug the component name is not the same as that is specified in the UIDL is 
~~~
        {
            "value": "contact-us",
            "meta": {
              "path": "/here-we-are",
              "componentName": "Us"
            }
          }
~~~

And the import statement is being generated properly
~~~
import Us from './pages/contact-us'
~~~

But the file name that is being generated is something like this 
~~~
contactus.css
contactus.js
~~~

**Comment by JayaKrishnaNamburu** [comment]
We can write a Github action to auto-deploy few sandboxes with the code that is being merged into master, to check if the generated components and projects are working fine, in such case we won't run into gotchas like this 😄 as before merging we can manually do a review of the sandbox one 😅

**Comment by JayaKrishnaNamburu** [comment]
We are running into this issue because of this line --> https://github.com/teleporthq/teleport-code-generators/blob/master/src/component-generators/react/react-component.ts#L80

Either use the same stringify method where we construct the import statement or pass sanitize it in resolve stage itself.

**Comment by JayaKrishnaNamburu** [comment]
To add something to this, if the user intentionally passes
~~~
{ meta : { fileName: 'contact-us' } }
~~~
we might run into the same scenario, we might need to resolve this attribute too.

**Comment by JayaKrishnaNamburu** [comment]
Hey, @alexnm / @vladnicula you guys checked this issue?

**Comment by alexnm** [comment]
I saw the bug yesterday, we have to have a working solution for all scenarios. the `meta` field will be become more important once we implement #20

**Comment by alexnm** [comment]
I might handle this part of #218
