### ISSUE TITLE
Add more tests

### ISSUE THREAD

**Issue by alexnm** [teleporthq/teleport-code-generators#178]
UPDATE from 21.05.2019:

Remaining tests:
- [x] integration tests on teleport-component-generator-react with a focus on 
   - [x] conditionals
   - [x] repeat node
   - [x] dependencies
- [x] integration tests on teleport-component-generator-vue
   - [x] conditionals
   - [x] repeat node
   - [x] dependencies
- [x] unit tests on teleport-plugin-x
- [x] unit tests on teleport-component-generator (the generic one)
- [x] unit test on teleport-generator-shared (with an extra focus on the files inside src/utils)

**Comment by anamariaoros** [comment]
Here is a list of test that could be added:
- [ ] integration tests on teleport-component-generator-react with a focus on 
   - [ ] conditionals
   - [ ] repeat node
   - [ ] dependencies
- [ ] integration tests on teleport-component-generator-vue
   - [ ] conditionals
   - [ ] repeat node
   - [ ] dependencies
- [ ] unit tests on teleport-plugin-x
- [ ] unit test on teleport-generator-shared ( with an extra focus on the files inside src/utils )
