### ISSUE TITLE
Handle non-element root for React component generator

### ISSUE THREAD

**Issue by alexnm** [teleporthq/teleport-code-generators#182]
With the new node based implementation for the UIDL structure, it's possible to define non-elements as the first node inside a component.

For example a component could start with a conditional node, a slot, or a repeat. It might not be a good practice, but we have to make sure we support all UIDL combinations.

The result of the `generateNodeSyntax` inside the `react-base` plugin is being cast to `JSXElement`:

```
const jsxTagStructure = generateNodeSyntax(uidl.node, {
      propDefinitions: uidl.propDefinitions || {},
      stateIdentifiers,
      nodesLookup,
      dependencies,
    }) as types.JSXElement
```

We need to handle other types of results her correctly

**Comment by JayaKrishnaNamburu** [comment]
Hey @alexnm can you elaborate a little bit about this, I will look into this

**Comment by vladnicula** [comment]
```json
{
  "$schema": "https://raw.githubusercontent.com/teleporthq/uidl-definitions/master/component.json",
  "name": "ImageElement",
  "stateDefinitions": {
    "isVisible": {
      "type": "boolean",
      "defaultValue": true
    }
  },
  "node":  {
    "type": "conditional",
    "content": {
      "reference": {
        "type": "dynamic",
        "content": {
          "referenceType": "state",
          "id": "isVisible"
        }
      },
      "value": true,
      "node": {
        "type": "element",
        "content": {
          "elementType": "text",
          "children": [{
            "type": "static",
            "content": "Now you see me!"
          }]
        }
      }
    }
  }
}
```

Will most likely fail. Not sure if it should work though :-?

**Comment by JayaKrishnaNamburu** [comment]
Will check this, currently ``Vue`` generator is not breaking as we wrap it inside ``template`` will check the react case.

**Comment by JayaKrishnaNamburu** [comment]
@vladnicula this UIDL does not break 👇 
~~~
{
    "$schema": "https://raw.githubusercontent.com/teleporthq/uidl-definitions/master/component.json",
    "name": "ImageElement",
    "stateDefinitions": {
      "isVisible": {
        "type": "boolean",
        "defaultValue": true
      }
    },
    "node": {
    "type": "element",
    "content": {
        "elementType": "text",
        "children": [{
            "type": "static",
            "content": "Now you see me!"
            }]
        }
    }
  }
~~~
because here the text node is returned is wrapped inside an HTML tag and is returned but the UIDL which you shared is breaking because since the only node which we have is conditional the generator will try to return something like this 
~~~
return ({status ? <span>This is from child</span> : <span>Status is false</span>});
~~~
which is causing us to run into such error, we can solve this by taking advantage of implementing React Fragements short [syntax](https://reactjs.org/docs/fragments.html#short-syntax) which i made an example here --> https://codesandbox.io/s/nw1ojo0o9l

By default, we can wrap our code with a fragment which won't render a div when the actual component is rendered.
~~~
return (
    <>
      {status ? <span>This is from child</span> : <span>Status is false</span>}
    </>
  );
~~~

**Comment by alexnm** [comment]
even if it fails, we should handle it somehow, check for that and show a warning or something in case of the `react` generator

**Comment by JayaKrishnaNamburu** [comment]
A possible way to fix if we want to support this kind of behaviors
1. Restricting the root to be always ``div`` 
2. We adding Fragment by default to the generated code.

**Comment by JayaKrishnaNamburu** [comment]
> even if it fails, we should handle it somehow, check for that and show a warning or something in case of the `react` generator

Yes, how about throwing an error in resolving phase? if the component json has only one element and that too conditional or some special cases like this?

**Comment by alexnm** [comment]
Not really, because this would be a `React` specific problem, so the `react-base-plugin` should throw that

**Comment by JayaKrishnaNamburu** [comment]
So @alexnm what do you say, we will throw error specifying to the user of we handle this scenario in the generators itself? Depending on that I will complete this PR today.

My opinion is as the primary end user is the UIDL Schema that is generated from the ``vision`` API we can just throw an error.

**Comment by alexnm** [comment]
So looking at what's possible in React, I'd say we should also make sure we can render these kinds of components:

#### Static nodes

```
"Test": {
  "name": "Test",
  "node": {
     "type": "static",
     "content": "test"
  }
}
```

should render
```
const App = (props) => 'test';
```

#### dynamic nodes
```
"Test": {
  "name": "Test",
  "node": {
    "type": "dynamic",
    "content": {
      "referenceType": "prop",
      "id": 
    }
  }
}
```

should render
```
const App = (props) => props.test;
```

#### conditional nodes
```
"Test": {
  "propDefinitions": {
    "test": {
      "type": "boolean",
      "defaultValue": false
    }
  },
  "name": "Test",
  "node": {
    "type": "conditional",
    "content": {
      "node": {
        "type": "static",
        "content": "test"
      },
      "value": true,
      "reference": {
        "type": "dynamic",
        "content": {
          "referenceType": "prop",
          "id": "test"
        }
      }
    }
  }
}
```

should render

```
const App = (props) => props.test && "static-string";
```

#### repeat nodes
same as above, a map returned from a React component is valid from React's perspective
