### ISSUE TITLE
Standardize generation options (for component and project)

### ISSUE THREAD

**Issue by alexnm** [teleporthq/teleport-code-generators#183]
I propose we have a single interface for `GeneratorOptions` for all component generators:

```
interface GeneratorOptions {
  localDependenciesPrefix?: string
  assetsPrefix?: string
  mapping?: Mapping
  skipValidation?: boolean
}
```

This is almost standard today, except for the style variation on the React side, which could be left as a separate parameter in the factory function for the react component generator.

Also, `GeneratorOptions` should be available both on the factory function as well as on the `generatorComponent` function to allow a flexible interface.

-----

Same story for `ProjectGeneratorOptions`:

```
interface ProjectGeneratorOptions {
  sourcePackageJson?: PackageJSON
  distPath?: string
  customMapping?: Mapping
  skipValidation?: boolean
}
```

Should be available on both the factory function and on the `generateProject` function

**Comment by vladnicula** [comment]
After writing a bit of the documentation, I'd say that the entire generator api needs a refresh. We keep repeating the same resolver and builder instantiations for every single factory function that build a component generator.

Maybe we can create a standard factory for components in the core as well which will build the function for us and always return a functions with the same signature.
