### ISSUE TITLE
Navlinks with state reference

### ISSUE THREAD

**Issue by alexnm** [teleporthq/teleport-code-generators#189]
Navlinks have an attribute `transitionTo` which is mapped at the moment to the `href` attribute or to the `to` attribute depending on the specific project flavor.

However, there's no transformation there for the content, so you have to specify the url as the attribute, ex: `/about-us`. It would be nice to be able to set only the state in which you wish to arrive (urls are just a meta info for each state value of the router).

So ideally, we should be able to set `about` as the attribute and the resolver will check the route stateDefinition and will extract the meta information (which url needs to go as a href/to for the navlink)

**Comment by JayaKrishnaNamburu** [comment]
Hey @alexnm can I start with this? since I don't have anything as of now.
