### ISSUE TITLE
Move teleport-repl as a package inside this monorepo

### ISSUE THREAD

**Issue by alexnm** [teleporthq/teleport-code-generators#207]
Pros:
- Any change in the core packages can instantly be tested in the repl environment
- All OSS contributions are counted on a single repo
- Easier to plan features/tasks with all issues on a single repo

Cons:
- Brings an additional project into a pretty big monorepo
- Should not have the same versioning system as the main packages, that might be harder to achieve now

**Comment by Utwo** [comment]
I think for the moment it's ok to leave repl in a separate repo, because we will run ```npm link``` only once in order to have the repos synchronized. Also if we want to merge this two repos, repl deployment will be a little harder and we will lose zeit github integration.

**Comment by alexnm** [comment]
removing this from release 0.7 as we still need to discuss about it during the next prep week
