### ISSUE TITLE
Default props are not being generated in case of only boolean prop is present

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [teleporthq/teleport-code-generators#213]
When our UIDL have only a single PropDefinition which is a boolean, the ``defaultProps`` and ``propTypes`` are not generating.

UIDL to replicate

~~~
{
  "$schema": "https://raw.githubusercontent.com/teleporthq/teleport-code-generators/master/packages/teleport-generator-core/src/uidl-schemas/component.json",
  "name": "SimpleComponent",
  "propDefinitions": {
    "test": {
      "type": "boolean",
      "defaultValue": true
    }
  },
  "node": {
    "type": "element",
    "content": {
      "elementType": "container",
      "children": ["Hello"]
    }
  }
}
~~~

**Comment by alexnm** [comment]
might be related or addressed in #12

**Comment by JayaKrishnaNamburu** [comment]
This was a temporary problem which was happening in old commits of #212 and not happening in master, so closing this.

**Comment by JayaKrishnaNamburu** [comment]
Figured out why it is happening, 

In this line we are checking if the ``defaultValue``. If it is present we are generating the ``propTypes`` so when we set the ``defaultValue`` to ``false`` it means the case cannot pass and so the ``propTypes`` are not being generated. I am taking care of this along with #12

**Comment by JayaKrishnaNamburu** [comment]
This issue happens in vue generators as well. I am taking care of this 👍
