### ISSUE TITLE
Styled-components / JSS imports should only appear when the component has style

### ISSUE THREAD

**Issue by alexnm** [teleporthq/teleport-code-generators#214]
Both style plugins currently add the dependencies even if no style is present on the component.

For styled-components it's:
```
import styled from 'styled-components'
```

For JSS it's:
```
import injectSheet from 'react-jss'
```
and the HOC
```
injectSheet(style)(Component)
```

**Comment by JayaKrishnaNamburu** [comment]
@alexnm this is happening only in the case of StyledComponents, for JSS it's working fine 🤔

**Comment by JayaKrishnaNamburu** [comment]
JSS --> https://github.com/teleporthq/teleport-code-generators/blob/master/packages/teleport-plugin-react-jss/src/index.ts#L74

**Comment by alexnm** [comment]
right, I got a wrong impression from an example probably
