### ISSUE TITLE
Replace .json files in testing folders

### ISSUE THREAD

**Issue by anamariaoros** [teleporthq/teleport-code-generators#229]
Currently, we have a lot of .json files in the `__tests__` folders that should be removed at some point. The only .json files we should keep are those in the `examples` folder.
Inside the testing files we should use uildl-builder functions from `teleport-generator-shared/src/builders`. The functions for project-uidl-builder should be implemented.

**Comment by JayaKrishnaNamburu** [comment]
Closing this as we have a duplicate here #206

**Comment by anamariaoros** [comment]
@JayaKrishnaNamburu Yes but this is not just replacement for json files. This also implies one has to do the func for project-uidl-builders. I'll update the #206
