### ISSUE TITLE
Generic function that builds the project folder structure

### ISSUE THREAD

**Issue by ionutpasca** [teleporthq/teleport-code-generators#233]
We currently have 4 project generators (react, next, vue, nuxt) dealing with creating all the necessary files for a working project. 
They are all composed by multiple steps (generate components from the UIDL, generate static files like package.json etc), among which is the folder structure building step (that takes all the generated components and places them in a folder hierarchy). 

This step is done in in every project generators and the code is very similar from one project generator to another:

```
export const buildFolderStructure = (
  files: Record<string, GeneratedFile[]>,
  template: TemplateDefinition
): GeneratedFolder => {
  const { componentFiles, distFiles, pageFiles, staticFiles } = files
  template.meta = template.meta || {}

  let { templateFolder } = template
  templateFolder = injectFilesToPath(templateFolder, null, distFiles)

  const componentFilesPath = template.meta.componentsPath || DEFAULT_COMPONENT_FILES_PATH
  templateFolder = injectFilesToPath(templateFolder, componentFilesPath, componentFiles)

  const pageFilesPath = template.meta.pagesPath || DEFAULT_PAGE_FILES_PATH
  templateFolder = injectFilesToPath(templateFolder, pageFilesPath, pageFiles)

  const staticFilesPath = template.meta.staticFilesPath || DEFAULT_STATIC_FILES_PATH
  templateFolder = injectFilesToPath(templateFolder, staticFilesPath, staticFiles)

  return templateFolder
}
```
This function is mostly the same in every project generator, the only difference being the number of file groups given as input; in this case we have ***componentFiles***, ***distFiles***, ***pageFiles*** and ***staticFiles***, but maybe in a different project generator we are only using the ***componentFiles*** and the ***pageFiles***.

-----------------------------------
It would be nice if we would have a generic function that can handle this operation, taking as input an array of files, their path in the folder hierarchy and generate the structure.

I would imagine that an interface for the input would look something like this:
```
interface FilesPathRecord {
  path: string[]
  files: GeneratedFile[]
}
```
where the path is an array of strings, every element from the array representing a folder in the structure. For example, if we have this path defined:
```
const path = [ 'src', 'components' ]
```
every file would go in a folder called **src** and then in a sub-folder called **components**

**Comment by alexnm** [comment]
@ionutpasca can we close this after the merge of #236 ?
