### ISSUE TITLE
Files names should be validated before assigning

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [teleporthq/teleport-code-generators#235]
If the UIDL name is having spaces in it, we are generated file names with spaces. We need to validate them before assigning.

Here is the reference --> https://github.com/teleporthq/teleport-code-generators/blob/master/packages/teleport-component-generator/src/index.ts#L68

This happens when the UIDL which we are using has its name like this

~~~
{
   "name": "Conditional Component"
}
~~~

**Comment by alexnm** [comment]
it happens because of the changes in #223, I'll check this out
