### ISSUE TITLE
Default values for Array and Object should be returned as functions in Vue

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [teleporthq/teleport-code-generators#238]
Currently, the default values for Array and Object w.r.t to Vue needs a little bit of refactoring. Here is how we are currently generating

~~~
props: {
    items: {
      type: Array,
      default: [],
    },
  },
~~~
and we are assigning the values in the data object like this
~~~
data() {
    return {
      isVisible: true,
      items: ['angular', 'vue']
    };
  }
~~~
But Vue throws errors to use the default value itself, and is not picking up the values from data when we have an object that is colliding with the same name in data.

When we don't have any colliding variables we should declare the default values like this
~~~
props: {
  arr: {
    type: Array,
    default: () => []
  },
 user: {
   type: Object,
   default: () => ({})
 }
}
~~~

**Comment by ionutpasca** [comment]
Hello @JayaKrishnaNamburu. This ticket will be closed by [this](https://github.com/teleporthq/teleport-code-generators/pull/279) PR.

The implementation from the PR solves the default value for Arrays and Objects returning them as functions and it also solves [this](https://github.com/teleporthq/teleport-code-generators/issues/210) issue.

The colliding related problem is fixed only for static data sources, used in the `repeat` type nodes, following to be fully fixed when we'll update the validation rules. @alexnm , please follow this.
