### ISSUE TITLE
Move github token into external file which is under .gitignore

### ISSUE THREAD

**Issue by alexnm** [teleporthq/teleport-code-generators#259]
In `teleport-project-packer-test` we have a placeholder for the github token which everyone needs to setup. Since that file is under version control, we might accidentally commit our tokens.

We should have two files:
- config.json
- config.example.json

the content should be:
```
{
  "token": "<your-token-here>"
}
```

Then the entry file of the package `index.ts` should read the `config.json` file and pass the token to the packer.

`config.json` should be added to `.gitignore`

The docs should be updated to specify that before running `npm start` you should do `cp config.example.json config.json` and generate a new token on github

**Comment by JayaKrishnaNamburu** [comment]
How about we use ``.env`` for this

**Comment by JayaKrishnaNamburu** [comment]
You can check it out here --> https://www.npmjs.com/package/dotenv

**Comment by alexnm** [comment]
@JayaKrishnaNamburu not needed since it's a simple token for the test project
