### ISSUE TITLE
Replace with build script instead of tsc

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [teleporthq/teleport-code-generators#310]
After merging the latest watcher, which waits for changes for files and builts it. We need to replace the **tsc** command with **build** command. Or, omit running build task for ``teleport-repl-component`` since repl have its own dev and build modes.

https://github.com/teleporthq/teleport-code-generators/blob/master/scripts/watcher.js#L20

**Comment by alexnm** [comment]
also if the new watch task is performant enough, we should remove all the dev:component / dev:project subtasks
