### ISSUE TITLE
Preact Styleguide

### ISSUE THREAD

**Issue by alexnm** [teleporthq/teleport-code-generators#317]
Since #314 we have another component generator, `teleport-component-generator-preact`. There are a couple of limitations for now and some explorations as well, which should be addressed with this issue:
- [x] css-modules is the only styling option, others can also be added with proper setups, but we need to test them out (eg: styled-components). inline-styles can also be added just as an example
- [x] css-modules also has an option to support both `dash-case` classes and `cameCase`. the standard preact css-modules setup does not support camelCase, so dash-case is explicit. However, with dash-case, the classes are generated like `class=styles['button']` even when there's no dash in the class name.
- [ ] preact examples seem to prefer destructuring the props and the state in the `render` function and assigning the default values there. would be a nice option on the base-plugin
- [x] `project-generator-preact` can be created with a setup based on the standard `preact-cli`

**Comment by JayaKrishnaNamburu** [comment]
Preact supports only `3.1.6` version of `styled-components`. Any upgrade from that version it won't work.

**Comment by alexnm** [comment]
I think we should check what are the good practices of the preact community to make sure we have support for that.

**Comment by alexnm** [comment]
closing this for now
