### ISSUE TITLE
UIDL Styles: Proposal for a different approach of how we manage styles 

### ISSUE THREAD

**Issue by vladnicula** [teleporthq/teleport-code-generators#337]
Managing styles in UIDL right now :

- Allows for setting basic styles on each node
- Has a little workaround for pseudo selectors and media queries
- Reusing styles is only possible by creating components and using component instances

After playing around with UIDL and using it in the Visual Editor we are working on we’ve noticed a few missing features:

1. We don’t have any way of defining reusable & compassable styles. 

Let’s say we have 3 types of buttons in a design we receive and have to build. Primary, secondary and default. In order to build the 3 buttons we could either:

- Build 3 components, all 3 of them using a basic button primitive with different styles
- Build 1 component that has a dynamic prop that decides how to change multiple style values and repeat the conditional check for the prop on each and every style key that we want to change.

This is not ideal. Let’s consider the case when we want to animate the button to a ‘disabled’ state. We would have to change 3 components, or seriously complicate the button from the second approach. 

2. Media queries and pseudo selectors are all mixed together  

When rendering styles from UIDL and displaying editors for them, we are having issues with media queries and styles that are applied to them because the nested node style is doing too many things.

We have to perform a string value check to decide if the content is a media query or a hover/after/before etc selector. This is a fuzzy way of doing guess work. The intention of the creator of the UIDL data is lost in this representation. They know precisely that they want to build a media query (or conditional style based on screen props for env like React Native), but the representation does not allow them to specify this.

3. There’s no way to define a set of default styles for primitives in UIDL.

Normally, on the web we rely on CSS resets. React Native envs have their own solutions for normalising things. With UIDL we don’t really know how a page really looks like until we use the generator of our choice. Each generator can include a different css reset and introduce artefacts because of it.

I think we found a potential solution to the first 2 problems, maybe even to the third one. Here goes:

We define the concept of ReusableStyleNode and ReusableStyles maps.

A ReusableStyleNode is a new type of node, defined in Project UIDL or Component UIDL. It will contain the style content similar to a css class, with some extras. The intended use for it is to be reference in a similar way to dynamic props in element nodes.

- A name that is unique in the scope that is defined in (this means that no two ReusableStyleSet of the same name can exist in on component or in one project. We can have the same name in two components and the project, but we cannot have the same identifier twice in one single component) 
- A set of conditional instructions to when this will be applied. This would contain things like css pseudo selectors, media queries, or a mix of both.
- The actual values, similar to what we have now on the style of element nodes, minus the nested styles of course.

This ReusableStyleNode can be referenced by Element Nodes, found in ReusableStyles which are Records<NameString, ReusableStyleNode> and applied to the nodes. With this approach, we could have reusable, compassable styles. 

The situation with the 3 buttons can be reduced to defining 3 style sets on the button. The additional loading state could be yet another ReusableStyleNode that is reference on the button only when needed, via a conditional node.

How to use in Element Nodes 

We would need a new key in Element Nodes that will reference an array of ReusableStyleNode references. 

How could this address the lack of CSS resets

We could have a special conditional instruction in the ReusableStyleNode that instructs the generators to target primitive tags. For example, if we want cursor pointer on all buttons, instead of making a class that is applied on buttons, or a component that has this style, we could define a DefaultPrimitiveStlyeNode:
- name: name of the component
- conditions: same conditions as before (like hover, media query etc)
- styles: etc

With this special kind of style node we would define project specific defaults for each primitive node, shifting the responsibility of default styles from uidl mappers into the project itself.

To think about:
- Should the conditional instructions like hover, media queries and so on be defined in ReusableStyleNode or in the reference that is defined in the Element Nodes. If we have the condition on ReusableStyleNode, it behaves a lot like css (media queries included). If we move it in the Element Nodes, it behaves more like a scss include/mixin.

**Comment by JayaKrishnaNamburu** [comment]
I was going through and thinking if this https://github.com/teleporthq/teleport-code-generators/issues/428 can be used to address the issue number 3. Reset CSS.

Right now in the UI, when we add any new element we kind of give some default styles for each element to make sure they look the same in all browsers. So, how about we configure global stylesheet with the default html elements that we support out if the box from the playground.

for example something like this 
**globalStyles**

```
body {
 margin: 0px;
}

div {
 margin: 0px;
padding: 0px;
}
```

And then we can take care of styles that are being changed or added in devMode.

**Comment by JayaKrishnaNamburu** [comment]
In the component level exports, we might need to pull the elements that are being used and add them.

 - Either UIDL can have it's own global Stylesheet.
 - Or we can have a styleMap = `{ body: {}, div: {} }` predefined in our project generators which merges with the UIDL global style sheet and then injected in the generated project.

**Comment by vladnicula** [comment]
> I was going through and thinking if this #428 can be used to address the issue number 3. Reset CSS.
> 
> Right now in the UI, when we add any new element we kind of give some default styles for each element to make sure they look the same in all browsers. So, how about we configure global stylesheet with the default html elements that we support out if the box from the playground.
> 
> for example something like this
> **globalStyles**
> 
> ```
> body {
>  margin: 0px;
> }
> 
> div {
>  margin: 0px;
> padding: 0px;
> }
> ```
> 
> And then we can take care of styles that are being changed or added in devMode.

Yes, that is the general idea of project based style sets. 

However do note that we have stayed so far away from having `css selectors` in UIDL, and rather we had them as a detail of implementation for the code generators. So, having that in mind, how do you target all `divs` in the project? Don't you have some kind of **reference** back from the div primitive to the particular style? 

Or to ask it differently, how would we implement css class selectors in unity for example. We have an ongoing conversation with some teams from unity to explore generating UIs for their game engine. They don't have css there, so all styles will have to be implemented differently.

**Comment by vladnicula** [comment]
> In the component level exports, we might need to pull the elements that are being used and add them.
> 
> * Either UIDL can have it's own global Stylesheet.
> * Or we can have a styleMap = `{ body: {}, div: {} }` predefined in our project generators which merges with the UIDL global style sheet and then injected in the generated project.

Again, it looks very similar to the initial suggestion, but with css selectors. I'm not sure that adding css selectors is the right move, as UIDL is supposed to be independent of the platform, and css is a very web specific thing, while component based uis are more generic.

**Comment by JayaKrishnaNamburu** [comment]
Ahh, this will limit the UIDL and the generators as well to the web and that's not the right move if we want to support unity then 🤔

**Comment by JayaKrishnaNamburu** [comment]
We might end of having different style sets for different platform of target and all of them need to be maintained regularly too !!

**Comment by JayaKrishnaNamburu** [comment]
@vladnicula  what if we build this global stylesheet at the time of selecting nodes from the UI ?. Right now when a element is added we add the defaults to the node itself. Instead we could add the defaults to the global sheet when the element is used. 

And the changes made using `devMode` or the changes from the style editor can be added on the node !!

**Comment by vladnicula** [comment]
> @vladnicula what if we build this global stylesheet at the time of selecting nodes from the UI ?. Right now when a element is added we add the defaults to the node itself. Instead we could add the defaults to the global sheet when the element is used.
> 
> And the changes made using `devMode` or the changes from the style editor can be added on the node !!
> 
> In this way, we won't be defaulting to any platform specific from the UIDL or generators side 🤔

I don't think I understand your proposal. We can have a set of global styles that are referenced by elements. So even if we don't add buttons in the uidl structure, we still have the button reusable styles in the project. This way we don't have complicate add / update / move / delete logic for  nodes. Think about conditional rendering. If we add styles to the global scope only when elements are added, we'll have some complex logic to deal with conditional rendering.

**Comment by vladnicula** [comment]
> We might end of having different style sets for different platform of target and all of them need to be maintained regularly too !!

I believe we can have one set of style definitions for all. 

For web, nodes referencing style nodes will be implemented by generating class names and css selectors. For other systems (flutter, unity etc) we will think of something else.

All systems generally have a set of common styling practice (font family, color, size in pixels or similar units of mesurement, flex layout - existed way before css 3 came out - etc). There might be some css props that won't make much sense in other systems, like transform, position absolute and such, but these could be either polyfilled in the generators for those specific platforms or we could restrict the adding of those style values based on target platform later on.

Either way, if we can have the same `element container` node on all platforms, I think we should and could have the same `border radius` or `font family` definitions for all platforms.
