### ISSUE TITLE
Plugin for TypeScript support in JSX based frameworks

### ISSUE THREAD

**Issue by alexnm** [teleporthq/teleport-code-generators#340]
Stencil has default support for TS, but it would be nice to have a plugin alternative to `teleport-plugin-jsx-proptypes` that can:
- declare a new type for the Props object
- declare a new type for the State object (only for Preact since React uses hooks)
- declare/specify the default props

**Comment by JayaKrishnaNamburu** [comment]
check this out --> https://github.com/lyft/react-javascript-to-typescript-transform
