### ISSUE TITLE
Replace $props and $state with proper JSON structure

### ISSUE THREAD

**Issue by alexnm** [teleporthq/teleport-code-generators#35]
In the UIDL if we want to address something from props, state, we rely on strings, hence the UIDL manipulation can seem a bit clunky (ex: `$props.message`, `$state.isVisible`)

We could talk about a JSON based structure for defining dynamic content (props, state, local vars - see #10)

A resolution on this should be made before the official release.

**Comment by vladnicula** [comment]
Currently discussing in #87 about a possible UIDL change that addresses this issue as well

**Comment by vladnicula** [comment]
Will be addressed in #87 as working on assets alone is way harder than updating the entire assignment of dynamic values flow

**Comment by vladnicula** [comment]
We should consider changing 

```
"content": {
        "type": "container",
        "name": "container",
        "children": [
          {
            "type": "text",
            "name": "title",
            "children": [...]
          },
```

to:

```
"content": {
        "type": "container",
        "name": "container",
        "children": [
          { 
              type: "component-instance",
              content: {
                "type": "text",
                "name": "title",
                "children": [...]
          }
 }
```

This will allow us to define children of type prop, or state, and not rely on `$props.propName` or `$state.stateName` structure. 

It also brings us closer to having a proper way of differentiating between a instantiation of a component and a declaration.

**Comment by vladnicula** [comment]
Latest update we're trying to implement is this: 

```js
{
   attrs: {
      src: {
            type: "dynamic",
            content: {
                  referenceType:"prop",
                  id: "avatarlURL"
            }
      },
      alt: {
            type: "static",
            content: "the author avatar"
      }
   }
}
```

**Comment by vladnicula** [comment]
@alexnm can we close this? We're done with it right? For beta 0.6 I mean.
