### ISSUE TITLE
Handling multiple statements in event handlers

### ISSUE THREAD

**Issue by alexnm** [teleporthq/teleport-code-generators#350]
When adding more than one statement in an event handler:
![Screenshot 2019-08-22 at 16 40 12](https://user-images.githubusercontent.com/9945366/63519429-98befe80-c4fb-11e9-8df0-78c38838e064.png)

The template part is properly updated to call a function, but the function is not implemented/added on the component class

![Screenshot 2019-08-22 at 16 40 04](https://user-images.githubusercontent.com/9945366/63519466-b12f1900-c4fb-11e9-9472-0c8780a31619.png)

Also notice the propCall is not handled, it uses the same syntax as vue, I think this is the solution we're looking for: https://angular.io/api/core/EventEmitter

**Comment by JayaKrishnaNamburu** [comment]
Can you share the UIDL please, UIDL/repl-link. Angular uses event emitter when it tried to pass something to the parent, where the component is being called. Like for example in react we pass callback functions as prop when we want to do some action when client goes on some change. So we need to differentiate between Event that we trigger back to parent or event that is happening in the component itself.

**Comment by alexnm** [comment]
https://repl.teleporthq.io/?uidlLink=n90rjgamaijr0nxq8bgif
