### ISSUE TITLE
Custom header and metadata support for Angular and Stencil

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [teleporthq/teleport-code-generators#363]
I was running all flavors in production env and headers are not reflecting for angular and stencil.

<img width="1044" alt="Screenshot 2019-09-17 at 10 12 38 PM" src="https://user-images.githubusercontent.com/11075561/65061790-478a1980-d998-11e9-894c-98ecdb308d61.png">

**Comment by alexnm** [comment]
I haven't seen a solution for stencil at the first search. Haven't looked for angular.

For vue/nuxt we use vue-meta, for react/preact we use react-helmet and for next we use the built-in functionality next/head
