### ISSUE TITLE
Navlink mappings for projects generated with Gridsome

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [teleporthq/teleport-code-generators#390]
We removed mappings from the `teleporthq/teleport-project-generator-gridsome`. So, when we start building projects with gridsome, the mappings are not reflecting and the route navigation is not working.

Codesandbos link --> https://codesandbox.io/s/5ylnf

Route navigation is not reflecting.

**Comment by alexnm** [comment]
ah my bad, this is not inherited from the vue project generator as the gridsome one uses just the vue component generator

**Comment by JayaKrishnaNamburu** [comment]
I will fix this then 👍
