### ISSUE TITLE
Resource paths for resource-loader react-native plugin

### ISSUE THREAD

**Issue by alexnm** [teleporthq/teleport-code-generators#393]
The resource loader plugin uses two ways of loading resources in react native components

```
if (sourcePath.includes(Constants.ASSETS_IDENTIFIER)) {
  // Assuming the components are generated next to the assets folder
  setResourceRequireCall(sourceAttrAST, `..${sourcePath}`)
} else {
  setResourceURIObject(sourceAttrAST)
}
```

For the local assets, we need a way of computing the path dynamically. Currently a `..` is appended, assuming that `components` and `assets` are two adjacent folders. But from the project strategy, you could set any kind of structure in theory

**Comment by JayaKrishnaNamburu** [comment]
We don't have react-native support at the moment, closing this for now.
