### ISSUE TITLE
Append prefix for the component names in Vue

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [teleporthq/teleport-code-generators#394]
Currently, in Vue, we are just importing the component and not appending any prefixes while using them. This works fine most of the time unless the name of the component collides with an HTML tag.

In Angular we append app so it generates

``<app-header></app-header>``

but in Vue it generates

``<header></header>`` which is works as an HTML tag instead of the component.

**Comment by alexnm** [comment]
fixed here: https://github.com/teleporthq/teleport-code-generators/commit/0f8f6ad7f25855e0de85bd8a7fd21d5f1959febe
