### ISSUE TITLE
Develop a cli for the component/project generators

### ISSUE THREAD

**Issue by alexnm** [teleporthq/teleport-code-generators#40]
Questions to answer:
- which would be the use cases for a cli?
- which library would help us to most with what we want?
- would the cli be a separate package?

**Comment by mihaiserban** [comment]
I think it would help if the team would create some user stories to help developers better understand where the product is heading, and what are the use cases.

Is this an accurate user story?

1. User opens the teleport visual editor
2. Starts editing the project, adds a title, adds input box, adds a submit button etc.
3. User is done editing, clicks export.
4. A generated project is downloaded.

In the following scenario I can see a job running, which would take a generated UIDL and pass it to a cli to generate the project, package it and return the generated code.

**Comment by alexnm** [comment]
That would be one scenario and is actually a great idea for a utility like service. We're naming this for now internally `project-packer` and it will probably take shape in the coming 2-3 weeks as an idea. 

What I had in mind with the notion of a `cli` for this was to bring the generators in the realm of the developers, for example for using them to start projects, but this is a bit far fetched for now

Once we have the documentation site online, we'll be able to better write down the future plans for the platform so that user stories can be created on the generators here.

**Comment by paulbrie** [comment]
The `project-packer` idea could also be a page where you can copy paste a UIDL, select a target, and download the code of the project.

**Comment by alexnm** [comment]
we were planning a discussion around the project packer some time in the coming weeks in the office. It is not tied to the `cli` idea as for now we just need a service that handle project generation based on some template. However, it might be interesting to discuss the idea moving forward.

@mihaiserban maybe you'd also like to get involved, we would be super happy to get some feedback on this

**Comment by mihaiserban** [comment]
@alexnm sounds interesting, i'd love to help

**Comment by alexnm** [comment]
this idea was slowly turned into the `project-packer` project, which will be started some time after JSHeroes. I'm closing this as we will open dedicated issues for that
