### ISSUE TITLE
Retain the files that are already existing in a folder while packing project

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [teleporthq/teleport-code-generators#403]
If we have any files in the sub fodler, at that time of project generation we are overwriting. This is making us to loose the existing files that are present in the folder.

**Comment by alexnm** [comment]
can you describe the scenario? is this when you're running the packer locally multiple times? or is it overwriting files from the template?

**Comment by JayaKrishnaNamburu** [comment]
ok, so lets think, the template is having a folder `src` and we have some files in it. Now, we need to inject few other files into `src` from our packer. At those cases, the files which are coming from the predefined template are missing
