### ISSUE TITLE
Extend the UIDL validator with business rules

### ISSUE THREAD

**Issue by alexnm** [teleporthq/teleport-code-generators#41]
UIDL validation is currently performed strictly on the JSON schema structure.

We could add a thin layer of validation for:
- prop that is being used without being defined in `propDefinitions`
- prop that is defined but not used in the content area
- state that is being used without being defined in `stateDefinitions`
- state that is defined but not used in the content area
- prop and state key are not the same? (this could work in React, but not in Vue)
- using local variables inside repeat:
   * using index without declaring `useIndex` in meta
   * using custom local variable name without specifying it in meta as `iteratorName`

Additionally for project generators:
- component is referenced but does not exist in the project
- component name is different than component key (in project UIDLs)
- external dependency version is consistent across the project
- `route` state key is defined inside `root`
- the first level children in the `root` component are conditionals based on `route`

**Comment by alexnm** [comment]
this is dependent on the implementation of the validation layer in #2

**Comment by JayaKrishnaNamburu** [comment]
Hey @alexnm is this available, i don't have much experience with resolvers, but would like to give a try and complete this 😃

**Comment by alexnm** [comment]
@JayaKrishnaNamburu I would wait for #140 to be merged into master. or you can start from that branch if you'd like. but this issue will require some changes after all the things we did for v0.6.

**Comment by JayaKrishnaNamburu** [comment]
Oh, ok i will wait for the master to be stable with the new changes and start with this, after a discussion for new changes instead of twice 😅

**Comment by JayaKrishnaNamburu** [comment]
Hey @alexnm since the 0.6 is merged can i start on this ?

**Comment by alexnm** [comment]
hey, I have a task to update this with the props specs, so not yet

**Comment by JayaKrishnaNamburu** [comment]
Ok, here are the few observations that we need to take care when doing this PR

1. #145 Misspelling of state identifier crashes the component generator
2. There is an edge case with all the style flavors. Basically, we are not doing a cross-check when the user is trying to refer a prop or state, we are generating the code. But when we try to run that only then we will know that the user did not declare them.
