### ISSUE TITLE
Potential naming conflict with StyledComponents

### ISSUE THREAD

**Issue by alexnm** [teleporthq/teleport-code-generators#412]
When the styled components tags are generated (eg: const Navbar = styled.nav) based on the names of the elements, the tags can be in naming conflict with the component itself.

One quick solution could be to check for that particular naming conflict and add a `Styled` prefix for that tag

**Comment by JayaKrishnaNamburu** [comment]
Hey, can you share a UIDL for this? That will be very helpful

**Comment by alexnm** [comment]
yes: https://repl.teleporthq.io/?uidlLink=d22l6ucm2emrnmrech2jpl
