### ISSUE TITLE
Repeat node is being appended to UIDL

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [teleporthq/teleport-code-generators#423]
While generating UIDL from markdown, i noticed a `repeat` node is being appended to the UIDL which we are passing and which is resulting in generating **jsx** syntax.

Here is the UIDL to replicate the issue --> https://repl.teleporthq.io/?uidlLink=jen8h8csetknuc9ct4dxfs

Once we pass the above UIDL through generators, it is adding the following node
```json
{
  "type": "repeat",
  "content": {
    "node": {
      "type": "element",
      "content": {
        "elementType": "li",
        "name": "item",
        "children": [
          {
            "type": "dynamic",
            "content": {
              "referenceType": "local",
              "id": "item"
            }
          }
        ],
        "key": "item"
      }
    },
    "dataSource": {
      "type": "dynamic",
      "content": {
        "referenceType": "attr",
        "id": "items"
      }
    },
    "meta": {
      "useIndex": true
    }
  }
}
```

**Comment by alexnm** [comment]
This is because of the mapping. It was an experimental idea, that the list can be an atomic element. If you want to bypass that, you can use `ul` and `li` and they won't be mapped with anything on top

**Comment by alexnm** [comment]
Can be seen here: https://github.com/teleporthq/teleport-code-generators/blob/master/packages/teleport-uidl-resolver/src/html-mapping.json#L134

**Comment by JayaKrishnaNamburu** [comment]
Yeah got it 👍
