### ISSUE TITLE
Handling code-blocks using UIDL

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [teleporthq/teleport-code-generators#424]
When parsing code-blocks and generating UIDL, we need a way to preserve the code blocks. Since they contain special characters in them, `uidl-validator` is failing to parse and continue the process. I tried by passing them as strings, it works but we will loose the format of the written code.

UIDL for replicating the issue --> https://repl.teleporthq.io/?uidlLink=c6237li2h35a90sux6dvyp

<img width="1132" alt="Screenshot 2020-01-28 at 12 06 53 PM" src="https://user-images.githubusercontent.com/11075561/73241267-8e4e1280-41c7-11ea-8f2e-b51de559e0ad.png">

**Passing them as string**
Code-sandbox link --> https://codesandbox.io/s/mu9bx

<img width="1280" alt="Screenshot 2020-01-28 at 12 17 29 PM" src="https://user-images.githubusercontent.com/11075561/73241519-41b70700-41c8-11ea-9110-e1cc45f84d6f.png">

We will loose the formatting for the code-block

**Comment by alexnm** [comment]
hmm. we had this issue in the playground. it was partially solved with an `encode` function that is here: https://github.com/teleporthq/teleport-code-generators/blob/master/packages/teleport-shared/src/utils/string-utils.ts#L60

maybe there are additional characters which need encoding in order to be preserved when the code is generated?

**Comment by JayaKrishnaNamburu** [comment]
Yes, we need to handle for the new line `/n`

**Comment by JayaKrishnaNamburu** [comment]
I just figured out, it's something related to the react side of the project. It's happening because the code is wrapped inside 
```html
<code>
 {code here}
</code>
```

So, react basically try to handle these as the dynamic values. We should be wrapping it inside a String literal and then while rendering should render inside a **pre** that and that does the job 👍

**Comment by JayaKrishnaNamburu** [comment]
I tried implementing this but this was a little trickier,  Here is the sandbox link --> https://codesandbox.io/s/0x0ib

If we need to preserve the code-format in react we need to output something like this 
```jsx
<pre>
  <code>
    {` 
     analog_rom.processor = promIpadBot; /n
     driveHeader.soft(modelOnlineTitle, minicomputerNativeDevelopment(/n
      bootEngineNorthbridge, sram, sram) - recycle);/n
    `}
  </code>
</pre>
```

Since we encode our special characters, the output is being generated like this

```jsx
<pre>
        <code>
          &#123;`analog_rom.processor = promIpadBot; driveHeader.soft(modelOnlineTitle,
          minicomputerNativeDevelopment( bootEngineNorthbridge, sram, sram) - recycle); if
          (wysiwygAnsi &lt;= -4) &#123; cameraDma = ivrTerabyteFull.emulation(2 + token);
          dns_boot.excel.truncate(fsbCdmaPrimary + northbridge); &#125; else &#123; pci -=
          botnet_cpl_cron; host.c_telecommunications_cad += tablet; &#125; ribbon(jreFavoritesWired,
          markupCompatibleVersion - streaming);`&#125;
        </code>
      </pre>
```

We need to preserve ``{`` and ``/n`` characters for the proper encoding.

**Comment by JayaKrishnaNamburu** [comment]
We solved this in the latest release, closing it 👍
