### ISSUE TITLE
article link is broken in readme

### ISSUE THREAD

**Issue by lisaiceland** [teleporthq/teleport-code-generators#431]
article link is broken in readme

**Comment by paulbrie** [comment]
Hi, thank you for reporting it. We'll fix it ASAP.

**Comment by paulbrie** [comment]
We found the issue. For now you can read the blog post here: https://teleporthq.io/blog-we-believe-in-a-i-powered-code-generation. We're going to patch it tomorrow.

**Comment by lisaiceland** [comment]
Nice! Thnx Got it.
Also, can you tell me how you are handling vulnerabilities (false
positives, other than just categorizing them as minor or mild) and in the
libs in the builds from different vendors and if breaking, how to you
mitigate them.

**Comment by paulbrie** [comment]
I'm not sure I got the question right. Could you give us more context - or an example - about the type of vulnerabilities your mentioning?  Is it a general question about how me manage our software lifecycle or something more specific?

**Comment by lisaiceland** [comment]
Hi Paul.
It's from the perspective of creating generators that incorporate
opensource libs, frameworks & SDKs that are open to potential attacks and
which are simply generated by the tools such as yours and no remediation is
going on at the front-end as checks. That's my question. e.g. Rekit using
CRA, etc.

Thank You. Bless.
Lis

Regards,

*Lisa Kristinardottir*
Subject Matter Expert (SME)
Lisaiceland <https://lisaiceland.com/>  |  Linkedin
<https://www.linkedin.com/in/lisaiceland/>
<http://ClinicalTrials360.com>

   P
*Save a tree! *
*Please let's ALL consider our environmental responsibility *
*before printing. *
*Don't print this e-mail unless it's really necessary.*

*CONFIDENTIALITY NOTICE*

This e-mail is intended only for the addressee named above. It contains
information that is privileged, confidential or otherwise protected from
use and disclosure. If you are not the intended recipient, you are hereby
notified that any review, disclosure, copying, or dissemination of this
transmission or taking of any action in reliance on its contents, or other
use is strictly prohibited.

If you have received this transmission in error, please reply to the sender
listed above immediately and permanently delete this message from your
inbox. Thank You.

**Comment by paulbrie** [comment]
Hi Lisa, it is indeed a good question.  

it is true that our generators depend on third party libraries. However, those libraries are open-source as well. Given this property, it is possible for various types of security scanners to confirm that at a given time, there are no known security issues with our software. If you are interested in learning more about these mechanisms we could organise a short call with our engineering team.

Even though this is good enough for most web applications, it is certainly not perfect: the scanners might have missed something, or we might have introduced unwillingly a vulnerability in our own code. But, at least, it's open-source, transparent, and traceable.

I also would like to mention that the code that we're generating is explainable in the sense that:
- it always reflects 1:1 the information contained by the underlying UIDL
- one can check at any point in the time the mechanics that generate code from our UIDL intermediary representation 

Anyway, thank you bringing up this topic. Each new level of automation comes with a lot of questions about the safeguards and we're very aware of this aspect regarding our technology.

If you have any specific case you'd like to discuss, let us know. :)

**Comment by lisaiceland** [comment]
Paul hi.
Thnx so much the response. Noted on the points.
I raised my concerns bc I'm seeing more and more of this happening with
multiple other generators other than Rekit I mentioned. But all good if you
guys stay vigilant for us all. We're all in this together after all.
Appreciate you all as always.

Thank You. Bless.
Lis

Regards,

*Lisa Kristinardottir*
Subject Matter Expert (SME)
Lisaiceland <https://lisaiceland.com/>  |  Linkedin
<https://www.linkedin.com/in/lisaiceland/>
<http://ClinicalTrials360.com>

   P
*Save a tree! *
*Please let's ALL consider our environmental responsibility *
*before printing. *
*Don't print this e-mail unless it's really necessary.*

*CONFIDENTIALITY NOTICE*

This e-mail is intended only for the addressee named above. It contains
information that is privileged, confidential or otherwise protected from
use and disclosure. If you are not the intended recipient, you are hereby
notified that any review, disclosure, copying, or dissemination of this
transmission or taking of any action in reliance on its contents, or other
use is strictly prohibited.

If you have received this transmission in error, please reply to the sender
listed above immediately and permanently delete this message from your
inbox. Thank You.
