### ISSUE TITLE
UIDL from the examples/project.json generates undefined links in the output.

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [teleporthq/teleport-code-generators#447]
The UIDL that we are currently using from the `examples/project.json` folder is generating *#undefined* links.

```js
        <textblock>
          <a href="#undefined">
            <span className={styles.text}>Get Started →</span>
          </a>
        </textblock>
```

**Comment by dhrubesh** [comment]
@JayaKrishnaNamburu to what I understand from https://github.com/teleporthq/teleport-code-generators/blob/master/packages/teleport-types/src/uidl.ts#L207
content doesn't accept `id` key it accepts `section`, replacing `id` with `section` resolves it, but I'm still getting several errors mostly around components which have `type: 'local'` when I run `npm run standalone`, are these 2 problems related?

**Comment by JayaKrishnaNamburu** [comment]
Hi @dhrubesh a recent update to master introduced this issue. The `project.json` needs some updates to run in the current master. I have handled it to run properly in an open pr. `feature/reusable-styles`. Which we will be merging soon. Please use that PR, if you want to get along the project till it gets merged in master. 😀

**Comment by dhrubesh** [comment]
@JayaKrishnaNamburu Looks like this issue resolved in `feature/reusable-styles`.

**Comment by JayaKrishnaNamburu** [comment]
Yes, i solved it. Just waitjng for it to merge. You can use it for now to understand the code 😀

**Comment by dhrubesh** [comment]
@JayaKrishnaNamburu I think https://github.com/teleporthq/teleport-code-generators/commit/b68472b845d76c08600370bea572e36c1d52baed this commit resolves it. Anyways, let me know if there are any more good first issue, I'll be happy to spend some time 😃

**Comment by JayaKrishnaNamburu** [comment]
That's the commit which actually introduced this, the current open PR solves it.

**Comment by JayaKrishnaNamburu** [comment]
Hi @dhrubesh the PR is closed now, and you can replicate this issue directly on master. Let me know if you want to have a shot at this issue, and if needed some help :smile:
