### ISSUE TITLE
Improve UIDL validation for global assets

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [teleporthq/teleport-code-generators#457]
For handling style tags, we need a string content or a path. But not both at the same time

```json
      {
        "type": "style",
        "content": " a {  text-decoration: underline; } button {  background-color: #fff; border-radius: 4px; border-color: #0089be; border-width: 1px; padding: 5px 10px; text-align: center; } input[type=text] {  border-color: #0089be; border-radius: 2px; border-width: 1px; } input[type=number] {  border-color: #0089be; border-radius: 2px; border-width: 1px; } textarea {  border-color: #0089be; border-radius: 2px; border-width: 1px; } svg {  fill: #2b2b2b; border-color: #2b2b2b; }"
      },
      {
        "type": "style",
        "path": "https://unpkg.com/pattern.css"
      }
```

Right now, we don't have a proper check. You can pass both content and path for the UIDL and it still works. But generates two tags. But ideally we should not allow this behaviour. Style tag either contains an external link or some self content.

- Supporting additational attributes or link tags like, `cross-origin` `integrity` etc will be a added advantage

**Comment by chavda-bhavik** [comment]
Hey @JayaKrishnaNamburu I've not found any validator that validates "assets" while checking in `teleport-uidl-validator/src/validator/utils.ts`. Is there any other place to check or we need to add new function that validates styles, font, icons in "assets".

**Comment by JayaKrishnaNamburu** [comment]
Hi, https://github.com/teleporthq/teleport-code-generators/blob/development/packages/teleport-uidl-validator/src/decoders/utils.ts#L163

So, we do validations in two phases. First we pass through these runtime type checkers and once it passes. We send then through thebactual validator which we see in validator/index.ts.

This is a good place to start  to divide icons and it's associated  values, style tag and scriot tag individually. Like how we did for events. Seperating "propCall" and "stateChange"

**Comment by JayaKrishnaNamburu** [comment]
And, for assets we just need type-checkers. Schema checks are more of business logics, like if we are using something and not defined in the UIDL etc. 😃

**Comment by chavda-bhavik** [comment]
@JayaKrishnaNamburu is this the way you were talking about to split the "assets"? This are the types I can think of for https://github.com/teleporthq/teleport-code-generators/blob/development/packages/teleport-types/src/uidl.ts#L22

```
    export interface UIDLScriptBaseAsset {
      type: 'script';
    }
    export interface UIDLScriptExternalAsset extends UIDLScriptBaseAsset {
      path: string
      options?: {
          async?: boolean;
          defer?: boolean;
      }
    }
    export interface UIDLScriptInlineAsset extends UIDLScriptBaseAsset {
      content: string;
    }
    export type UIDLScriptAsset = UIDLScriptExternalAsset | UIDLScriptInlineAsset;
    
    export interface UIDLStyleBaseAsset {
      type: 'style';
    }
    export interface UIDLStyleExternalAsset {
      type: 'style';
      path: string;
    }
    export interface UIDLStyleInlineAsset {
      type: 'style';
      content: string;
    }
    export type UIDLStyleAsset = UIDLStyleExternalAsset | UIDLStyleInlineAsset;
    
    export interface UIDLFontAsset {
      type: 'font',
      path: string
    }
    export interface UIDLCanonicalAsset {
      type: 'canonical',
      path: string
    }
    export interface UIDLIconAsset {
      type: "icon",
      path: string,
      options?: {
          iconType?: string;
          iconSizes?: string;
      }
    }
    export type UIDLGlobalAsset = UIDLScriptAsset | UIDLStyleInlineAsset | UIDLStyleExternalAsset | UIDLFontAsset | UIDLCanonicalAsset | UIDLIconAsset
```

**Comment by JayaKrishnaNamburu** [comment]
Looks, good. How about we remove `UIDLScriptBaseAsset` and just include the `type` for `UIDLScriptExternalAsset` and `UIDLScriptInlineAsset` directly. Like how `UIDLStyleAsset` is being defined. And we are not using `UIDLStyleBaseAsset`. So please remove `UIDLStyleBaseAsset` and `UIDLScriptBaseAsset`. The idea is just not too have too many bases and extensions. Or we might end up exporting too many and confusing with too many, for just a `type` attr. 

But if the `bases` has more, definitely what you proposed is the best way to go 😄

**Comment by chavda-bhavik** [comment]
There will be decoders for each asset but do we need to add validations for assets in `validator/utils.ts`? and for this we need to add tests?

**Comment by JayaKrishnaNamburu** [comment]
No need, `type-checkers` itself validates the input 😄. And we don't have inter dependent stuff here. So, schema-validators are not needed 😄
