### ISSUE TITLE
Update semanticType and elementType check

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [teleporthq/teleport-code-generators#464]
Right now, at instances we can just pass `semanticType` and no need for `elementType`. Like in case of library imports etc. In those instances we need to send empty strings for `elementType` just to pass the validator. Update the validator to not throw error, if `semanticType` is present and `elementType` is still missing.

https://repl.teleporthq.io/?uidlLink=01pltn0kj2donw9rbjo206l

**Comment by alexnm** [comment]
but that's valid only for `elementType` = `component`. also from the structure of the UIDL Element Node, semanticType is optional, because elementType is the fallback, so I would keep it as required

**Comment by JayaKrishnaNamburu** [comment]
Agreed 👍, I was just little confused between the components imported from libraries to components imported from local folders.
