### ISSUE TITLE
External library dependencies are missing from final package.json file

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [teleporthq/teleport-code-generators#470]
## Problem

When a node is using any external dependency, example dependency type as `library`. These dependencies are missing from the final `package.json` file.

Here is an example node which uses external library
```js
{
  "type": "element",
  "content": {
    "elementType": "component",
    "semanticType": "Button",
    "children": [],
    "dependency": {
      "type": "library",
      "path": "antd",
      "meta": {
        "namedImport": true
      }
    },
    "style": {},
    "attrs": {
      "type": {
        "type": "static",
        "content": "danger"
      }
    },
    "abilities": {},
    "referencedStyles": {}
  }
}

```

When using a component generator on top of this, we get the following code
```js
import { Button } from 'antd'
```

But the final `package.json` is missing these external dependencies. Here is the `package.json` at the end.

```js
"dependencies": {
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-router-dom": "5.1.2",
    "react-helmet": "^5.2.1",
    "react-scripts": "3.2.0"
  },
```

**antd** is missing from the project's `package.json` file.

Codesandbox url --> https://codesandbox.io/s/lvs5u

## Solution

**antd** should be added to the `package.json` at the end if it is being used.

**Comment by alexnm** [comment]
there's a confusion with naming here. type library should be a dependency that comes from the framework (eg: react, react router, next/head) so we don't add it because it is part of the project template. Type package should be used in this case. But I suggest we improve the naming to avoid this confusion in the future

**Comment by JayaKrishnaNamburu** [comment]
I switched it to `package` but it still doesn't seem to add in the `package.json`

**Comment by alexnm** [comment]
maybe `collectedDependencies` has a bug, but that's where the package dependencies are gathered to ensure they are added later in package.json

**Comment by JayaKrishnaNamburu** [comment]
@alexnm i wasn't sending `version` and so it is missing from the `package.json` file at the end. I just refactored the `type` and the `validator` check here #471
