### ISSUE TITLE
allow for custom UIDL json schema

### ISSUE THREAD

**Issue by paulbrie** [teleporthq/teleport-code-generators#48]
We could think of allowing custom UIDL JSON schemas as well. It would be needed for custom integrations and/or custom code generators.

**Comment by vladnicula** [comment]
What do you mean by custom UIDL JSON? Custom how? More fields? Different field names? What exactly?

**Comment by paulbrie** [comment]
I think about a mechanism which would allow the extension of our JSON schema with extra fields that would match the needs of custom generators we would not be in charge of. From our perspective, it would mean only to allow the user to add as a parameter their own custom UIDLs.

**Comment by vladnicula** [comment]
I see... So basically we need to allow the UIDL validator to accept new rules? Because right now that's the only part that prevents us from adding custom keys in the JSON.

**Comment by alexnm** [comment]
I think this is a bit further down the line. The current validator package allows easy customization, so we could swap the schemas if needed at some point
