### ISSUE TITLE
Rename Now to Vercel

### ISSUE THREAD

**Issue by alexnm** [teleporthq/teleport-code-generators#489]
We have several instances of interfaces and functions with now, including the now publisher. We should rename everything to vercel to ensure consistency with the playground

**Comment by creativenull** [comment]
Hey! May I have a go at this?

**Comment by JayaKrishnaNamburu** [comment]
yeah sure @creativenull, please go ahed 😄 . And let me know if you have any difficulties in setting the dev env

**Comment by creativenull** [comment]
Hey, sorry it took long (busy week). Making a PR.

**Comment by JayaKrishnaNamburu** [comment]
Thanks for the PR @creativenull 😄
