### ISSUE TITLE
Consider adding optional chaining operator in generators code (not generated code)

### ISSUE THREAD

**Issue by vladnicula** [teleporthq/teleport-code-generators#49]
We could consider adding the optional spread operator in the generator code. We could benefit from it a little bit as it allows us to write more or less the same code in less lines but without sacrificing readability in my opinion. 

Link to tc39 proposal: https://github.com/tc39/proposal-optional-chaining

Link to typescript discussions about it: https://github.com/Microsoft/TypeScript/issues/16

The main target of this exploration would be to see if we can use optional-chaining now, maybe via a babel plugin that runs before typescript in the babel pipeline.

**Comment by alexnm** [comment]
@vladnicula did you do anything with this on the playground? should we still keep this issue open here?
