### ISSUE TITLE
the teleport-component-generator-react is not work when attrs's value is false

### ISSUE THREAD

**Issue by A-FE** [teleporthq/teleport-code-generators#492]
## example
```json
{
    "type": "element",
    "content": {
        "elementType": "text",
        "attrs": {
            "isCard": {
                "type": "static",
                "content": true
            },
            "extra": {
                "type": "static",
                "content": false
            }
        },
        "children": []
    }
}
```

## expect
```
<span isCard extra={false}></span>
```

## actually
```
<span isCard extra></span>
```

**Comment by JayaKrishnaNamburu** [comment]
Hi @good-father thanks for reporting this, reproduction url --> https://repl.teleporthq.io/?uidlLink=xeki4sl1lbio9w7wn1xut

**Comment by A-FE** [comment]
@JayaKrishnaNamburu I am sorry, I can't. when I click the button "Share UIDL", the request "https://us-central1-croapp-dev.cloudfunctions.net/repl-api/upload-uidl" is always pending, I try to ping "us-central1-croapp-dev.cloudfunctions.net", but it is not work.

**Comment by JayaKrishnaNamburu** [comment]
Hi @good-father i already made a reproduction url to reproduce the bug here --> https://repl.teleporthq.io/?uidlLink=xeki4sl1lbio9w7wn1xut

I will take a loot at this bug by the end of day. If you are interested in fixing it, i would like to help too 😄

**Comment by A-FE** [comment]
@JayaKrishnaNamburu I'd love to fix it 😄 , I will pull request later

**Comment by JayaKrishnaNamburu** [comment]
Sure, thank you. Let me know if you need any help in project setup 👍

**Comment by A-FE** [comment]
@JayaKrishnaNamburu Hi, please review my PR #493
