### ISSUE TITLE
error package.json name using yarn, illegal character space + uppercase

### ISSUE THREAD

**Issue by mihaiserban** [teleporthq/teleport-code-generators#51]
Yarn doesn't allow spaces or uppercase letters in project name. Should change the name to teleport-project maybe.

"name": "teleport project",

`➜  dist git:(master) ✗ yarn install
yarn install v1.9.4
error package.json: Name contains illegal characters
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.`

```
String does not match the pattern of "^(?:@[a-z0-9-~][a-z0-9-._~]*/)?[a-z0-9-~][a-z0-9-._~]*$".
The name of the package.
```

**Comment by alexnm** [comment]
yes, good catch! we haven't had time to test the project generators with real life examples yet and we are just mapping the `name` plainly from the UIDL. we should tokenize (if that's the word) the name to make it `package.json` friendly

**Comment by mihaiserban** [comment]
i think slugify is better than a random generated token ;) keeps it human readable

**Comment by alexnm** [comment]
slugify is what I had in mind, but missed the word :)
