### ISSUE TITLE
[proposal] allow for user custom eslint rules for code generation

### ISSUE THREAD

**Issue by mihaiserban** [teleporthq/teleport-code-generators#52]
It would be nice for the code generator to read custom formatting rules provided by the user and apply them to the generated code classes.

This could be an additional step to the code generation such as - `prettier-eslint --write`

for example styles in the generated code are not formatted correctly.

<img width="316" alt="screenshot 2019-02-28 at 20 42 33" src="https://user-images.githubusercontent.com/3420526/53590163-d587e980-3b99-11e9-891b-0417b859ab5b.png">

**Comment by alexnm** [comment]
in #65 I extracted the prettier options into `constants`. we can treat those as the default settings and add a `prettierConfig` parameter in the `GeneratorOptions` interface, then overwrite the default settings with that at build time

**Comment by paulbrie** [comment]
I reported the style jsx issue in #67 as this is not related (only) to prettier.

This is what you get without prettier:

```javascript
import React from "react";import PropTypes from "prop-types";
const Card = props => {
  return <div className="card">{props.item}<style jsx>{`
          .card {
            margin: 10px;
            border: 1px solid black;
            padding: 10px;
          }
  `}
    </style></div>;
};
Card.propTypes = {
  "item": PropTypes.string
};
Card.defaultProps = {
  "item": "placeholder"
};
export default Card;
```

The closing `'}` is at the same level with the `return` and neither babel or prettier seem to know how to deal with it. I'll add a specific fix for this case.

**Comment by mihaiserban** [comment]
Works pretty well in prettier playgrounds, you can copy their config and see the output.

https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgCU4BDMAgMxwnXwB0QdTyGBuDbPfABWswBUAnpjgBnfFRr0QmPgFoYwsWzpRIUUQQDCJHABN8AXnyyImcYYB8+YKvz4mMAK44o+ADx7UAN3xgANiSiogByJOhwhgxgunoMlsCm5gB0qPDoAL7umoL+cPgAVqIAHgkABnb2VdXJMfo2ldVN+Oi6AOaoUEj4AIwADJjFrI3NVQBGuHpwON09g-iiEP6oBmOBYADWw26j1Zgkel5QbbMDQyPNGZVlVzv27gD0OXmWj17eltsZ2zr6yUlCEQWBo7BhpODoBjdXhmQFiZKaHCdNqqb6qX56ZJTCgkJz+GAw8xGEH2MHpKHSTDrOAACyWUxwDFR2zgxU4BGxuPx+AxrBAABoQGYYKhoKJkKBdNQAO7cXQIcUoEjeCArAUgMY4MgbOAwADK+zAyOQMBwTjggppMHQ-gA6jTwaJDXA9Qq0j40oJkOBgurOqJpgStW1Wsgcf4A4KisUAEJaza6vXhOAAGU6cDDJAjFpA0b1yLyAEUnBB4Jns4L9jgAzhvWMSGNctB1bJOjBbSsYDTkAAOPqV6gB21azDe2RiabeDOCpgARycqCYvBIIZI5cjIAD6FQJrNOdEBbgxdLGaQ4Y3MAbHb0XeQACZBaaSKhlsctDRQygoNBpyAnAH+AbRVzzgDIMiAA

**Comment by mihaiserban** [comment]
you can reproduce the same behaviour in prettier playgrounds by enabling --require-pragma
probably related to that.

**Comment by paulbrie** [comment]
I just tried in our code base with their config and it didn't work. I'll try in isolation. Thanks for the suggestion!

**Comment by paulbrie** [comment]
https://codesandbox.io/s/zk6q26226x

I tried it isolated in Codesandbox, where it behaves as in our code (and not like in Prettier's playground). 
Am I missing something?

**Comment by paulbrie** [comment]
I've opened an issue: https://github.com/prettier/prettier/issues/5943

**Comment by mihaiserban** [comment]
that's probably for the best, i wasn't able to get it running in isolation as well 🤷🏻‍♂️

**Comment by paulbrie** [comment]
Mystery solved: we need to use the `postcss` parser as well for CSS-in-JS.
Working demo: https://codesandbox.io/s/zk6q26226x
Do you want to take care of this one? :)

**Comment by mihaiserban** [comment]
> @mihaiserban: do you want to take care of this one? :)

sure ☺️

**Comment by mihaiserban** [comment]
https://github.com/teleporthq/teleport-code-generators/pull/68 ✨ much better 😉

**Comment by alexnm** [comment]
I'm closing this as I'll add a new issue to allow sending parameters to the new concept of `postProcessing` functions, used in the generation process. the prettier format is done via these functions, so we need a way to pass formatting options here
