### ISSUE TITLE
Project UIDL validation passes even when routes are not defined

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [teleporthq/teleport-code-generators#538]
There are a multiple cases in which the **Project UIDL** validator is failing.

1. Validator passes even when the `route` definitions are not defined in the project. 
2. The check for route shouldn't always happen in the `route` atts. Because we can have the routes defined under any `attr` key. and use that as reference.
3. ProjectUIDL should have at-least on route defined
4. Throw a error if the `root` node is missing `Router` element and the child's `conditional` uidl nodes.

**Comment by chavda-bhavik** [comment]
Hey, @JayaKrishnaNamburu I've tested removing the "Router" element from the root node, removing "router" from stateDefinitions, and with an empty array for "route" in stateDefinitions for react-project.json file, the validator is throwing error. Is there any other way I can look into this issue?

**Comment by JayaKrishnaNamburu** [comment]
Hi @chavda-bhavik i will take a look at these conditions again and share some reproducible links. You can take a look at this #457 if you are looking for something related to `validations` in mean time 😄

**Comment by JayaKrishnaNamburu** [comment]
I tested this, looks like we are supporting all the above mentioned validations. Closing this 😄 👍
