### ISSUE TITLE
Add a CHANGELOG.md file

### ISSUE THREAD

**Issue by alexnm** [teleporthq/teleport-code-generators#54]
There are some solutions for automating the changelog creation.

Also, it shouldn't be a priority until we hit v1.0 since changes will occur rapidly now in alpha/beta versions

**Comment by JayaKrishnaNamburu** [comment]
Hi i have few ideas how the change logs can be managed, can i work on this, will share the flow how we can add this 👍

**Comment by alexnm** [comment]
Hey, we were thinking of using something like this: https://github.com/fabiospampinato/bump

What do you have in mind? we're open to suggestions and of course all the issues are up for grabs

**Comment by JayaKrishnaNamburu** [comment]
My suggestion is this --> https://github.com/semantic-release/semantic-release and if we are looking for something which is related only to changelog then we can have a look at this --> https://github.com/danger/danger-js which reviews the PR and comments if updating a Changelog is not done.

**Comment by alexnm** [comment]
semantic-release looks perfect for this, I guess it works well with commitizen enforced commit messages, which we're trying to add here as well

**Comment by JayaKrishnaNamburu** [comment]
Can i give a try in implementing for this repo and see how it goes ?

**Comment by alexnm** [comment]
sure, we would love to get your contribution. however, there's one little catch, especially with semver, we cannot go to `1.0` because our entire ecosystem is still in alpha/beta versions. not sure if there's a way to bypass this with the package. other than that, feel free to give it a try ;)
