### ISSUE TITLE
Validate Prop and State Definitions to handle special characters

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [teleporthq/teleport-code-generators#545]
If we have special characters in `propDefinitions` and `stateDefinitions`. The generated code breaks, because these don't follow valid naming conventions in JS.

For validating naming conventions --> https://www.javascript.com/learn/variables

Example --> https://repl.teleporthq.io/?uidlLink=o34zl8vnv0buuxc3vc7pp&flavor=Stencil

**Comment by chavda-bhavik** [comment]
@JayaKrishnaNamburu I would like to work on it. Do validators/decoders have anything for this check? and do we allow special characters?

**Comment by JayaKrishnaNamburu** [comment]
So we can do this in 2 step process, first either validate and throw error. Or during resolving phase, replace the special characters with something usable. I am lookong more at, handling on the generators side. Like, instead of throwing error let's convert them. How does that sound  ?

**Comment by chavda-bhavik** [comment]
That would be a great idea, converting them to something like underscore can work, if it's not affecting other functionalities.

**Comment by JayaKrishnaNamburu** [comment]
Yup, we just need to make sure the references are also changed. I would see this change should happen inside `resolvers` like `teleport-uidl-resolver`. Please let me know if you need any help 😄

**Comment by JayaKrishnaNamburu** [comment]
@chavda-bhavik if you started working on this, that's fine. But i will share few pointers that will make it easy to work on this in the morning 😄. Because when i started thinking about the fix, i will we can use `codeFriendlyName` or something like that in `AST` generation phase.

**Comment by chavda-bhavik** [comment]
Thanks, @JayaKrishnaNamburu. It would be very helpful if you also say where can I look to make changes.

**Comment by chavda-bhavik** [comment]
Hey @JayaKrishnaNamburu, can you provide the points you were talking about, that need to be taken care of. And where should I look to work on this issue?

> @chavda-bhavik if you started working on this, that's fine. But i will share few pointers that will make it easy to work on this in the morning smile. Because when i started thinking about the fix, i will we can use `codeFriendlyName` or something like that in `AST` generation phase.

**Comment by JayaKrishnaNamburu** [comment]
@chavda-bhavik sorry for the delay was little onto other PR's and stuff. Will share now 😄

**Comment by JayaKrishnaNamburu** [comment]
So @chavda-bhavik  here is a simple example i have created again to give the gist of the issue.  From the repl link https://repl.teleporthq.io/?uidlLink=47cde49c-f8d1-49e9-9080-d28f7cce013b&flavor=React&style=CSS-Modules

You can see that when i define my `propDefinition` as `heading#`. The code passes thorough validation. But fails in `post-process` since it is invalid name. So, for this we need to remove any `illegalCharacters` that are not supported for naming.

You can do this by writing a quick resolver, you can find more on resolvers here https://github.com/teleporthq/teleport-code-generators/blob/development/packages/teleport-uidl-resolver/src/resolver.ts#L32

You can use `UIDLUtils.removeIllegalCharacters` on top of any dynamic `prop` or `state` reference. And on the `propDeefinitions` and `stateDefinitions`. Instead of adding them at every place in the generators.

**Comment by chavda-bhavik** [comment]
hey @JayaKrishnaNamburu,  I couldn't able to figure out the way to add a resolver and test it. Can you help?

- Do I need to write a resolver in teleport-uidl-resolver/src/utils.ts that validate the name right? Or we need to format variable names?  
- Resolvers used at https://github.com/teleporthq/teleport-code-generators/blob/development/packages/teleport-uidl-resolver/src/resolver.ts#L32, runs when are we parsing the UIDL right?
- And if we need to create a resolver then to do a check, do I need to create Element as did [here](https://github.com/teleporthq/teleport-code-generators/blob/development/packages/teleport-uidl-resolver/__tests__/resolver.ts#L51), and then to test them?

**Comment by JayaKrishnaNamburu** [comment]
Hey @chavda-bhavik, I will set up a branch in your fork 😄, with some initial setup and explaining how these resolver things work. But i can do that tomorrow morning 😅, need some time to arrange that. Sounds good ?

**Comment by chavda-bhavik** [comment]
Okay @JayaKrishnaNamburu, thank you.

**Comment by JayaKrishnaNamburu** [comment]
Heya @chavda-bhavik just a small update, i am trying to change the whole build pipeline here https://github.com/teleporthq/teleport-code-generators/pull/577
Once that is done, the build time comes down from 10-13mins to just a couple of seconds. So didn't update anything here, because it will end up causing a lot of merge conflicts if we start with this. I will wrap by monday and share it with you

**Comment by JayaKrishnaNamburu** [comment]
Hey @chavda-bhavik can you sync your fork with the latest changes once, I tried it, but forgot i don't have permissions there. Can you add me to the repo there ?

**Comment by JayaKrishnaNamburu** [comment]
@chavda-bhavik i am closing this. Let me know if you would like to pick something else here. I spent some 2 days on this. But there are lot more side-effects if we handle this. Ideall it should be handled by the platform that is generating UIDL. So thank you, closing now.
