### ISSUE TITLE
 Publish declarations files under the @types organization on npm

### ISSUE THREAD

**Issue by mihaisampaleanu** [teleporthq/teleport-code-generators#55]
Publish teleport-code-generators declarations files under @types/teleport-code-generators

More info: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by alexnm** [comment]
one thing that is not clear to me, is it enough to specifiy the types path in `package.json` like in the doc and bundle them with the npm package? or you also should push them to the @types org on npm?

**Comment by paulbrie** [comment]
As far as I know, it is not required if we already have them in our `package.json`. However, that forces the user to download everything even if the only need is just to type. We should check for best practices.

**Comment by vladnicula** [comment]
<img width="1088" alt="Screenshot 2019-03-22 at 10 00 43" src="https://user-images.githubusercontent.com/126038/54808699-ad1b7880-4c89-11e9-8489-80d0888138d9.png">
It seems they make it very clear that the "best practice" for projects written in typescript, like ours, is to publish them with the package, not as a separate "@types/package-name" thing.

**Comment by alexnm** [comment]
@mihaisampaleanu should we close this? we have the `types` linked in `package.json`

**Comment by vladnicula** [comment]
@mihaisampaleanu @alexnm we don't have to close it. Someone needs to move the interfaces into a types declaration file, instead of exporting them and importing them where neeeded.

**Comment by alexnm** [comment]
@vladnicula would you like to take this?

**Comment by vladnicula** [comment]
on it.
