### ISSUE TITLE
Test Architecture/Structure

### ISSUE THREAD

**Issue by alexnm** [teleporthq/teleport-code-generators#63]
Questions to answer
- do we keep tests separated from the library code?
- if so, how do we structure the tests inside the `__tests__` folder? mirroring `src`?
- would a split into `unit`, `integration`, `performance`, `e2e` work better inside the tests folder?

Let's figure out the best approach here

**Comment by paulbrie** [comment]
I vote for:

- keep tests separate from the library code
- mirroring `src`
- yes, split into `unit`, `integration`, `performance`, `e2e`

**Comment by alexnm** [comment]
RESOLUTION: the current setup is ok, we just need to add more tests for specific areas where unit testing is needed. 

The test categories will be: `unit`, `integration` and `performance` for now
