### ISSUE TITLE
performance metrics

### ISSUE THREAD

**Issue by paulbrie** [teleporthq/teleport-code-generators#64]
It would be great if we could track the performance of our code-generators over-time. I would like to suggest the following approach:

- test 3 components of `simple`, `medium` and `high` complexity/size
- the test should measure (1) the code generation itself, (2) the prettier pass, (3) the total
- the tests should be run for each tag/version on the same computer
- this should be done before each tag/version publication

**Comment by alexnm** [comment]
we might consider this as an experiment - https://github.com/prettier/prettier/issues/1059

**Comment by alexnm** [comment]
also we could leverage the parseAST function which is internal in prettier - https://github.com/prettier/prettier/issues/4675#issuecomment-396653791

**Comment by mihaiserban** [comment]
https://github.com/zeit/next-stats-action here's a good starting point, not sure if you've seen Zeit's PR stats compare.
I assume this could be adapted to run a github action on each new tag/version, and post them to a github thread, so you won't have to worry about storing the data.

**Comment by mihaiserban** [comment]
Here's a starting point.

I've used circleci to trigger a job when pushing a new tag. 

1. checkout repo https://github.com/mihaiserban/teleporthq-perf-stats
2. gets repository tags
3. for each tag version runs setup for a test project using @teleporthq/teleport-code-generators@tag-version package
4. generate components from 3 UIDL samples and record time in ms and code size in bytes.
5. report results for each version on a github issue: https://github.com/mihaiserban/teleporthq-perf-stats/issues/1 (needs formatting)

As far as i know you can't listen to hooks for other repos, so a circleci config will need to be added to the teleporthq repo in the end.

I assume there will be breaking changes to UIDL, at some point the UIDLs won't be valid for older tags, and will stop reporting.

<img width="1602" alt="Screenshot 2019-04-04 at 21 53 15" src="https://user-images.githubusercontent.com/3420526/55581042-9a428280-5724-11e9-8169-d43b2e7a0411.png">

**Comment by alexnm** [comment]
the perf tests we have now, running on both `react` and `vue` show that for an average component, the generators run in approx 200ms (out of which 60ms is the post-processing with prettier)

For a big component (2000 nodes), processing time varies:
- 2.5s for React (out of which 2s is the prettier format)
- 6s for Vue (out of which 5s is the prettier format)

I will create a task to develop a custom light formatter for html, since prettier is an overkill specifically for html code.
