### ISSUE TITLE
Link node that has a css class bound to it will not have the class added to it after code generation

### ISSUE THREAD

**Issue by vladgrecu** [teleporthq/teleport-code-generators#653]
STR:
1. Create a node
2. Bind a CSS class to it
3. Check generated code
Expected: <a> tag gets renderer with the CSS class on it
Actual: no CSS class bound to the generated <a> tag

**Comment by JayaKrishnaNamburu** [comment]
Adding a bit more context to the bug, this happens only when we assign a `routeLink` to a node in NextJS and the node to have some styles.

In cra, we use `Link` from `react-router-dom` and it spreads all the props received from the users as attrs on the `a` tag. 
https://github.com/remix-run/react-router/blob/main/packages/react-router-dom/index.tsx#L281=
And so, the class-name we generate is passing to the node.

```jsx
<Link to="/" className="footer-link">
      Static website builder
</Link>
```

converts into 

```html
<a class="footer-link" href="/">Static website builder</a>
```

But in case of `Link` from `next/link`
```jsx
<Link href="/page" className="footer-link">
     <a>Static website templates</a>
</Link>
```
is generated into

```html
<a class="jsx-80f6f96a92cbc09" href="/page">Static website templates</a>
```

the `footer-link` is not forwarded to the anchor tag. And so we have missing styles in the project.
