### ISSUE TITLE
Add support for TailwindCSS

### ISSUE THREAD

**Issue by jdnichollsc** [teleporthq/teleport-code-generators#691]
Hey folks, thanks for this great plugin for figma, it would be great if you can export the styles using TailwindCSS.

Please let me know what you think! ❤️

**Comment by JayaKrishnaNamburu** [comment]
Hey @jdnichollsc i just released a plugin to help ppl use tailwind classes in the UIDL directly and the exported projects will be pre-configured with tailwind. So, users can use classes like `text-gray-100`, `hover:text-purple-500` etc while designing and the projects exported consists of tailwind in them. 

Here is an example in the UIDL
https://github.com/teleporthq/teleport-code-generators/blob/development/examples/uidl-samples/project-tailwind.json#L562

And the example to use tailwind with the UIDL project export
https://github.com/teleporthq/teleport-code-generators/blob/development/packages/teleport-test/src/standalone.ts#L254

These changes will eventually lead into https://play.teleporthq.io, where you can directly use tailwind to design :)

**Comment by JayaKrishnaNamburu** [comment]
You will be able to export 8 frameworks pre-configured with tailwind once you use it for designing out of the box at the moment
https://github.com/teleporthq/teleport-code-generators/pull/689
