### ISSUE TITLE
create a couple of playable demos in codesandbox

### ISSUE THREAD

**Issue by paulbrie** [teleporthq/teleport-code-generators#70]
I'd love to have a series of playable demos in codesandbox. I suggest that we add our ideas in comments.

**Comment by vladnicula** [comment]
Probably not the best idea ever, but might get this conversation going:

A super simple, minimal drag and drop of images, titles and paragraphs with a resulting code under it? No nested levels of containers, just one flex parent that can get as many images, text and paragraphs as it wants. :-?

**Comment by paulbrie** [comment]
Interesting, I like the idea... A sort of mini playground? :)

**Comment by vladnicula** [comment]
Exactly. Mini playground, super simple, to get a taste of the potential it has. It's very hard to appreciate the power of the generators without a visual tool to accompany it.

**Comment by JayaKrishnaNamburu** [comment]
I tried in implementing a [prototype](https://github.com/JayaKrishnaNamburu/teleport-playground) here currently it just renders a static components.

**Comment by vladnicula** [comment]
@JayaKrishnaNamburu  Sweet! I did not know about https://github.com/JayaKrishnaNamburu/teleport-playground/blob/master/src/App.js#L37. I wonder if we could have similar things for Vue and frameworks. Having the ability to render the generated code without pushing it to a server and serving it from another host would be great. 

I'll check it out more in the future if we decide to actively work on this. I'll also post here an update if I do get a drag and drop mini editor running.

**Comment by JayaKrishnaNamburu** [comment]
> @JayaKrishnaNamburu Sweet! I did not know about https://github.com/JayaKrishnaNamburu/teleport-playground/blob/master/src/App.js#L37. I wonder if we could have similar things for Vue and frameworks. Having the ability to render the generated code without pushing it to a server and serving it from another host would be great.
> 
> I'll check it out more in the future if we decide to actively work on this. I'll also post here an update if I do get a drag and drop mini editor running.

I think this is completely possible, up to my knowledge I believe codesandbox does that for all the front end applications like in-browser execution, will do some research on that 👍

**Comment by alexnm** [comment]
@paulbrie / @vladnicula should we close this for now and re-open when we have some concrete examples in mind?
