### ISSUE TITLE
Guide on how to setup editor locally

### ISSUE THREAD

**Issue by vatsalsmehta** [teleporthq/teleport-code-generators#702]
Hi guys can someone please guide me or refer me to some documentation that'll help me in setting up the editor locally and get it running .
I want to be able to use the drag and drop editor and create its respective json file or code file locally.

**Comment by JayaKrishnaNamburu** [comment]
The editor which you access at play.teleporthq.io is not open-source. You can get to more information about generators here https://docs.teleporthq.io/guides/getting-started.html

**Comment by vatsalsmehta** [comment]
Okay can you tell me whether its developed inhouse or available to users at some pricing model over internet ?

**Comment by JayaKrishnaNamburu** [comment]
It is developed in-house, the app is available as a SaaS here https://teleporthq.io. Would like to know more about your use-case. You can reach to me on discord at  jkrishna#7322
