### ISSUE TITLE
How to get UIDL from form components?

### ISSUE THREAD

**Issue by crocodile305** [teleporthq/teleport-code-generators#714]
This repository is very helpful for me.
But I have one question.
How to get the UIDL data from form components?
Please help me with which plugins or packages are used to get UIDL from form components.
Thank you.

**Comment by JayaKrishnaNamburu** [comment]
Are you looking for generating UIDL from a existing component. If so, the generators can't do that. It just works one way for now. Take the UI and generates component. If you want to generate UIDL, you can do that using [teleporthq.io](https://teleporthq.io)
