### ISSUE TITLE
src folder structure

### ISSUE THREAD

**Issue by paulbrie** [teleporthq/teleport-code-generators#72]
@alexnm 
What do you think about the following structure?

```
+ src
|--  core
|-+  generators
  |--  component
  |--  project
|--  plugins
|--  shared
|--  uidl-defintions
| index.ts

**Comment by alexnm** [comment]
I think it depends on what we decide with #30, if we use lerna, we have a totally different approach in structuring the folder

**Comment by alexnm** [comment]
I will close this as we move the discussion to #30
