### ISSUE TITLE
Add plugin for styled-components

### ISSUE THREAD

**Issue by alexnm** [teleporthq/teleport-code-generators#73]
Being a pretty popular solution, it would be a shame not to have it as an option for the generated React components

**Comment by vladnicula** [comment]
I could take a look at this when I get freed up a little :)

**Comment by alexnm** [comment]
@mihaisampaleanu also was curious to try this

**Comment by vladnicula** [comment]
I'm happy to setup help then since I've built most of the stlyedjsx/jss plugins :)

**Comment by vladnicula** [comment]
We should wait for #87 to be ready before we add any more style flavours
