### ISSUE TITLE
Scripts in Components throws an Error in nextjs exported code.

### ISSUE THREAD

**Issue by technoknol** [teleporthq/teleport-code-generators#734]
Accordian and Navbar has some JavaScript which causes variable is already declared error when user navigates to other page.
This code may be causing issue for other libraries as well, but I haven't checked yet.

I have fixed that by moving script from render method to `useEffect`.

Working code for Navbar
```
useEffect(() => {
        // Mobile menu
        const mobileMenu = document.querySelector("#mobile-menu")

// Buttons
        const closeButton = document.querySelector("#close-mobile-menu")
        const openButton = document.querySelector("#open-mobile-menu")

// On openButton click, set the mobileMenu position left to -100vw
        openButton.addEventListener("click", function () {
            mobileMenu.style.transform = "translateX(0%)"
        })

// On closeButton click, set the mobileMenu position to 0vw
        closeButton.addEventListener("click", function () {
            mobileMenu.style.transform = "translateX(100%)"
        })
    }, [])
```

**Comment by JayaKrishnaNamburu** [comment]
@technoknol can you share any reproduction or the project that is exported. Because as far as i remember, code-generators can't generate any `js` code inside `useEffect` hook. Is the script added by you or already present inside when exported the code ?

**Comment by technoknol** [comment]
@JayaKrishnaNamburu I used `Finbest finance app` template, which has mobile responsive nav and an accordian on home page. Try to export it to next and host it on vercel or run from local. Home page will work fine but as soon as you navigate to other page, you will get an error like `mobileMenu is already defined`. Because navbar and accordian component has vanilla script inside it. 

p.s. Sorry I can't share project as it's for one of the client.

**Comment by JayaKrishnaNamburu** [comment]
@mihaisampaleanu @elizamaria are we injecting code into components now ?

If so, any code injections should happen only in `useEffect` or else they keep running every time react component refreshes

**Comment by JayaKrishnaNamburu** [comment]
Related to #733

**Comment by paulbrie** [comment]
I'm taking a look at it. Will be back with updates ASAP.

**Comment by paulbrie** [comment]
It's an error in the script not the generators, will fix the script.
