### ISSUE TITLE
Render conditional statement based on props/variable

### ISSUE THREAD

**Issue by alexnm** [teleporthq/teleport-code-generators#75]
So far we experimented with state handling and rendering blocks of UI conditionally based on state conditions. Example:
```
{isExpanded && <div>{props.text}</div>}
```

where `isExpanded` is a state key inside the component.

But conditional rendering can done based on a prop value or some local variable. We're basically talking about an `if` implementation in the UIDL / generators.

**Comment by vladnicula** [comment]
For all those state and props switches between one text to another I see state machine as being a better option. We might be able to get away without having if statements, only some inline ternaries which decide a state key in which the app might be. 

We should discuss this further at some point :-?

**Comment by JayaKrishnaNamburu** [comment]
Hey guys what do you think, is this issue and #118 are related? I mean since we are planning to have a change on how we are going to handle the structure for handling does that effects this? I am not sure, if it effects, I would like to pick that up (#118 ) and then I will come for this

**Comment by JayaKrishnaNamburu** [comment]
Hey, @alexnm / @vladnicula  any updates on this?

**Comment by alexnm** [comment]
@JayaKrishnaNamburu it is highly dependent on the changes we're making on `release/0.6` branch. I'd say we wait a bit with this, because it might be done all-in-one. The extent of the changes can be visualized in my latest comment in #105

**Comment by JayaKrishnaNamburu** [comment]
ok @alexnm I see there is a lot of discussion happening around structuring schema, trying to catch up with all that 😅  , is there any issue related of v0.6/v0.5 that i can start with that from today 😄
