### ISSUE TITLE
Asset Representation in UIDL

### ISSUE THREAD

**Issue by vladnicula** [teleporthq/teleport-code-generators#79]
Right now assets like background images and image srcs are "decided" when reading that node, they are not declared. We sort of figure out we are dealing with assets, we don't know for sure.

This creates a few problems as it does not allow us to:
- distinguish between local assets and remote ones and handle them separately 
- perform any kind of optimization on them
- support anything else apart from urls that get consumed from a remote location

I suggest we write down a list of assets we think would be most commonly used in components and start to think of a representation for them, then test it out and see how many types of assets the representation can handle.

I'd add the following assets, which could go both in components but also project wide:
- Images
- SVGs
- Video
- Fonts
- Binary / Downloadable 
- Audio 

And would specify that we could treat the assets in a couple of ways:
- Save to local project: would download / copy the assets and create a folder structure for them in the folder structure of the project. 
- Remote: will not touch the asset, and let it be unchanged, exactly like the url specified 
- Custom: will allow some sort of transformation inside our generators, for example, for SVGs in a react component we could download them, store them in a folder and use a React SVG loader to treat them as React Components. For a font we could write a handler that also generates the required CSS (for web) or Styles(for native) needed to render and use that font across the project.

**Comment by paulbrie** [comment]
Very interesting. A question: couldn't we infer all the asset categories from the URI of the asset?

**Comment by vladnicula** [comment]
No, because both local and url based schemas can have custom urls to normal assets. Example 'https://mycnd.com/get-me-custom-font' could serve a font. There's no imposed convention on having a specific file type at the end. In a similar way I can save a image as a 'image.private' name in my local file system.

**Comment by paulbrie** [comment]
I understand. I was counting on the extension convention for that. Could we eventually enforce the type declaration only in the case of undetectable types? Otherwise, we might have to declare that `image.png` is a PNG image. 🤔

**Comment by vladnicula** [comment]
I think we only need to know it's a image, not a png to properly treat it. So a type has a set of file extensions. Something like
```
{
   asset: "image",
   path: "url or path to asset"
}
```

**Comment by vladnicula** [comment]
Closing this as https://github.com/teleporthq/teleport-code-generators/issues/87 is now open with a change proposal for assets support.
