### ISSUE TITLE
unique id checks

### ISSUE THREAD

**Issue by paulbrie** [teleporthq/teleport-code-generators#84]
I propose that we add a checking mechanism which issues a warning if in a page there is a duplicate `id` attribute.

**Comment by JayaKrishnaNamburu** [comment]
That's a nice idea, how about a linter plugin which helps in throwing errors at the time of writing schema itself in their IDE's that should eliminate again cross validation in UIDL validation step ?

**Comment by alexnm** [comment]
@paulbrie do you mean the `key` field on each content node in the UIDL? that is automatically generated by the `resolvers`

**Comment by paulbrie** [comment]
@alexnm I have to check with you that I understand correctly how the `key`field is treated. What I would like to achieve is that the generators avoid unique id collisions in the generated code. Is this taken into account currently?

**Comment by alexnm** [comment]
currently we need unique identifiers for classnames and that is solved by the key generaration at component level, where each node from a component has a different key, even if they have the same name.

for example, if two nodes have the name "container", the keys will be: "container" and "container1"
