### ISSUE TITLE
Html script tag with type "module"

### ISSUE THREAD

**Issue by LittleSantaClaus** [teleporthq/teleport-code-generators#891]
In the latest vite+vue projects, the main script is connected with type "module":
```html
<script type="module" src="/src/main.ts"></script>
```

But in progect-generator the script type is hardcoded and cannot be changed to any other value.

https://github.com/teleporthq/teleport-code-generators/blob/3cd81f19b5358e1b5f71e7c9ef610258fc3f0210/packages/teleport-project-generator/src/file-handlers.ts#L290

Maybe there is another option how to specify the type?
Or maybe add the ability to specify the script type in progect-generator?

**Comment by JayaKrishnaNamburu** [comment]
@LittleSantaClaus can we know your requirements please. Right now, we don't have a export with `vite` yet. So, i am just curios onhow this is obstructing. 
And on a side note. We can extend it by passing `attrs` for script. Just like how we are passing for style nodes in UIDL
https://github.com/teleporthq/teleport-code-generators/blob/development/packages/teleport-types/src/uidl.ts#L127-L130

```ts
export interface UIDLStyleInlineAsset {
  type: 'style'
  content: string
  attrs?: Record<string, UIDLStaticValue>
}
```

**Comment by LittleSantaClaus** [comment]
I'm trying to set up a custom generator for a vite+vue 3 project.

Unfortunately, passing `attrs` is not implemented for assets in this place, so I started looking for workarounds

But in the end I found a better solution - to describe this import in a strategy rather than a UIDL.
Because it seems that this `script` tag is a generator configuration, not a specific project.

I think this issue can be closed. Thanks!

```js
const strategy = {
  entry: {
    // ...
    options: {
      customTags: [
        {
          targetTag: 'body',
          tagName: 'script',
          attributes: [
            { attributeKey: 'type', attributeValue: 'module' },
            { attributeKey: 'src', attributeValue: '/src/main.js' }
          ]
        }
      ]
    }
  }
}
```

**Comment by JayaKrishnaNamburu** [comment]
@LittleSantaClaus glad the workaround was helpful. Let me know, of you need any other help on the new generator. Will be happy to help
