### ISSUE TITLE
Support for UIDLElementNode as UIDLAttributeValue

### ISSUE THREAD

**Issue by julia-alberici** [teleporthq/teleport-code-generators#897]
The use case:

I want to be able to generate code that contains an element as an attribute of another element, one example using ReactJS would be using the component TextField from Material UI lib wich contains the prop "inputComponent" that can receive a component:

`<TextField
  InputProps={{
    inputComponent: MyInputComponent,
    inputProps: {
      component: SomeThirdPartyComponent,
    },
  }}
/>;`

This is quite simple to support to React, but I'm not sure about the other frameworks generators.
I have some ideas to do almost the same to Angular but I have no idea if this is possible to the others generators.

Can you share your thoughts about it? If you think it's viable I can work on it myself :)

**Comment by JayaKrishnaNamburu** [comment]
Hello @Julia-Alberici thanks for opening this issue. I understood the requirement and i am implementing similar to this in #163. Would you be interested in testing this out.
