### ISSUE TITLE
Handling boolean attributes in XML chunks

### ISSUE THREAD

**Issue by alexnm** [teleporthq/teleport-code-generators#9]
Boolean values are not properly transformed into html attributes

ex: `disabled: true` becomes `disabled="true"`, not simply `disabled`

**Comment by JayaKrishnaNamburu** [comment]
Hi, I would like to work on this if this is still available.

**Comment by alexnm** [comment]
@JayaKrishnaNamburu please go ahead and thank for your contributions :)

**Comment by JayaKrishnaNamburu** [comment]
The project and the concept behind it look so awesome 😄  I just need a little help in setting up the dev environment 😅 that would be very helpful to contribute more.

How to use the generators in another project where we are importing them, like I usually use ``npm-link`` but I don't think it helps in this scenarios as the ``@teleport.teleport-code-generators`` need to be imported in another project to test out the UIDL is generating proper output.

**Comment by alexnm** [comment]
sure, thanks for your interest. let me know if there's anything I can help with.

if you want just to test the generators, you can run the example project generators, there are all sorts of scenarios with the UIDL there. check the `npm run create-react-next` and other similar tasks in `package.json`.

furthermore, there's the `__tests__` folder which imports the code from the `src` index file and is pretty similar with installing the generators from `npm`

**Comment by paulbrie** [comment]
@JayaKrishnaNamburu You can also check this working example on Codesanbox: https://codesandbox.io/s/230qkz73jj
Let me know if it is useful for your onboarding, we're thinking of creating several code sandboxes like this one to get people started.

**Comment by JayaKrishnaNamburu** [comment]
Thank you @alexnm and @paulbrie will try all these and get back to you if any help needed 🙂

**Comment by JayaKrishnaNamburu** [comment]
Hey, while I was checking the docs I felt UIDL is the most important thing in the whole concept and thought it will be so great if there is an online playground for users to get used to in writing UIDL.

With initial thoughts, I have tried out something like this
![demo](https://user-images.githubusercontent.com/11075561/54589292-46a91700-4a4b-11e9-84d0-562d04c2cfb5.gif)

Would like to know your opinions on this 😄

**Comment by JayaKrishnaNamburu** [comment]
And @paulbrie need a small help in recreating the issue, is the ``disabled: 'true'`` is happening on input boxes or some specific components when I tried out ``disabled`` in code sandbox on input box the output doesn't even have a disabled property 🤔  

<img width="1262" alt="Screenshot 2019-03-19 at 1 47 10 PM" src="https://user-images.githubusercontent.com/11075561/54590281-b8826000-4a4d-11e9-9242-d0e12a62c108.png">

**Comment by alexnm** [comment]
@JayaKrishnaNamburu, great remark, we're also looking into building an online editor for the UIDL, we just want to have the Vue generators on par with the React ones in terms of capabilities.

In your example with the `disabled` attribute, you need to put it inside `attrs` like this:

```
{
  "type": "input",
  "attrs": {
    "disabled": true
  }
}
```

I started working on this branch - https://github.com/teleporthq/teleport-code-generators/tree/45-vue-on-par related to #45, so please take a look at the first changes as I'm trying to isolate the functions that are doing xml manipulation.

**Comment by alexnm** [comment]
I just noticed that the generators are crashing for vue because we're assuming all the attributes are strings.

@JayaKrishnaNamburu do you mind if I take this over? as it will probably be mixed with the work I'm doing on the vue generators, which are not up to date with the latest developments of the UIDL.

**Comment by JayaKrishnaNamburu** [comment]
> I just noticed that the generators are crashing for vue because we're assuming all the attributes are strings.
> 
> @JayaKrishnaNamburu do you mind if I take this over? as it will probably be mixed with the work I'm doing on the vue generators, which are not up to date with the latest developments of the UIDL.

Sure you can go ahead, I will take some other issue 😄

**Comment by alexnm** [comment]
I can suggest UIDL related issues, so you can get more familiar with the UIDL schema and how the UIDL is represented: #18 and #19 

Also if you want to work a bit with the babel types and ASTs, there's #14 

Finally, this one is a bit messier, but could use some help with generating the proptypes for React #12

**Comment by alexnm** [comment]
@allcontributors[bot] please add @JayaKrishnaNamburu for code

**Comment by JayaKrishnaNamburu** [comment]
And @alexnm I am not sure if you were aware of this behavior, 

``UIDLValidators.validateComponent`` is returning an array of objects which was ideally supposed to be the behavior in case of invalid UIDL, and true in case of a valid UIDL ([reference](https://github.com/teleporthq/teleport-code-generators#uidl-validators))

I was using the same schema example that was suggested in the [repo] but it is returning objects.

(https://github.com/teleporthq/teleport-code-generators/blob/master/examples/uidl-samples/component-author-card.json)

<img width="674" alt="Screenshot 2019-03-19 at 2 29 47 PM" src="https://user-images.githubusercontent.com/11075561/54593248-2598f400-4a54-11e9-8f9f-d3f4e4800838.png">

**Comment by alexnm** [comment]
`validateComponent` is returning the result of the ajv validation library. yes, an array of errors in case the json does not match the schema. at some point we would need to show nice messages out of that array, for now it's just the raw data

**Comment by JayaKrishnaNamburu** [comment]
> `validateComponent` is returning the result of the ajv validation library. yes, an array of errors in case the json does not match the schema. at some point we would need to show nice messages out of that array, for now it's just the raw data

No, I mean I am passing a valid UIDL which I just took from the repo which is a valid one and should not throw errors right, the code is being generated properly but `validator` says the schema is invalid which i case the generator also should crash or throw errors 🤔

**Comment by paulbrie** [comment]
@JayaKrishnaNamburu could you please copy/paste here the sample? We'll check.

**Comment by JayaKrishnaNamburu** [comment]
Here is the output of the UIDL component validator
~~~
[
  {
    "keyword": "type",
    "dataPath": "",
    "schemaPath": "#/type",
    "params": {
      "type": "object"
    },
    "message": "should be object"
  }
]
~~~

This the [sample](https://github.com/teleporthq/teleport-code-generators/blob/master/examples/uidl-samples/component-author-card.json) i used.

**Comment by JayaKrishnaNamburu** [comment]
Hey, @paulbrie looks like its not the problem with the UIDL sample 😅my bad, it's happening when I stringify the UIDL and again apply parse on it, it's happening in this case.

**Comment by alexnm** [comment]
this issue will be closed when merging #45 since I switched the html rendering to [rehype](https://github.com/rehypejs/rehype)

**Comment by JayaKrishnaNamburu** [comment]
Is it something the the generation of code from AST to html or jsx is done with rehype now ?

**Comment by alexnm** [comment]
yes, changes are on this branch: https://github.com/teleporthq/teleport-code-generators/pull/83 which is WIP
