### ISSUE TITLE
Release cycle of UIDL changes

### ISSUE THREAD

**Issue by vladnicula** [teleporthq/teleport-code-generators#90]
We should define a strict release cycle of uidl changes. What I mean by this is that we need to define what type of work can be done directly on master, like hot fixes of generators, and what cannot be added into master.

UIDL declaration changes should not be added into the master directly. I think we should create a separate main branch where we accumulate UIDL changes which will be pushed into master only once in a few months or so, with clear documentation of what has changed, and why.

Depending on how much adoption we have, we should decide if we implement this differentiation now or in the future.

**Comment by alexnm** [comment]
related a bit to versioning, which is a discussion topic here #29

**Comment by alexpausan** [comment]
Now, the the UIDL has as a required property **schema**. This is ok to make the validation but maybe it should not be required. If it's not sent, the current/latest schema can be used. Or if you have other ideas I'm happy to discuss

**Comment by vladnicula** [comment]
The default schema makes sense. What I am talking about is not how we validate the schema, but how often the new versions of the UIDL schema get released. I believe we need a lifecycle for releasing schema updates, and only keep support for 2 or 3 schema versions.

**Comment by alexnm** [comment]
the schema will be fixed at `v1` in sync with the generators 1.0.0 release. when we need a different schema, we should bump the major UIDL version to v2 and the generators will be in 2.0.0
