### ISSUE TITLE
Optimize boolean states in <template>

### ISSUE THREAD

**Issue by alexnm** [teleporthq/teleport-code-generators#93]
Currently, a boolean state renders something like this
```
<span v-if="isExpanded">Collapse</span>
<span v-if="!isExpanded">Expand</span>
```

In terms of good practices for the vue generators, we might render boolean states correlated with `v-if` / `v-else`.

This is similar to #14, which we are doing for the React generators

**Comment by JayaKrishnaNamburu** [comment]
Hey @alexnm can I pick this up?

**Comment by alexnm** [comment]
please do. not sure about vue best practices, but check if there are other alternatives to the v-if/v-else attributes

**Comment by JayaKrishnaNamburu** [comment]
Sure @alexnm I am new to ``Vue`` but will try my best 😅

**Comment by JayaKrishnaNamburu** [comment]
should fix #99  (just referring as I started working on this)

**Comment by JayaKrishnaNamburu** [comment]
@alexnm you can close this now

**Comment by alexnm** [comment]
yes, thank you!
