### ISSUE TITLE
Event handlers optimization for Vue components

### ISSUE THREAD

**Issue by alexnm** [teleporthq/teleport-code-generators#95]
Event handlers are added on the `methods` object in a Vue component. However, when an event handler has a single instruction, like a state assignment, it can be inlined in the template.

Instead of generating:
```
<button @click="handleButtonClick">
```
and adding a function on component methods:
```
methods: {
  handleButtonClick() {
    this.isExpanded = !this.isExpanded
  },
},
```
we could set the state inline
```
<button @click="isExpanded = !isExpanded">
```

**Comment by JayaKrishnaNamburu** [comment]
Hey @alexnm i would like to work on this, is this available ?

**Comment by alexnm** [comment]
yes please, go ahead ;)

**Comment by JayaKrishnaNamburu** [comment]
Raised a PR 😄 will check something else now
