### ISSUE TITLE
Dangerous characters encoding in Vue templates

### ISSUE THREAD

**Issue by alexnm** [teleporthq/teleport-code-generators#96]
When generating the `html` for the vue templates, we're using `hast-util-to-html`.

We need to investigate how to bypass the characters encoding for `&`, `'` and other special characters that the vue templates might have inside string attributes.

Example: When using a complex conditional render based on an AND between two operations, we get this
```<span v-if="(activeTab >= 3) &#x26;&#x26; (activeTab < 5)">This is the fourth tab</span>```
instead of this
```<span v-if="(activeTab >= 3) && (activeTab < 5)">This is the fourth tab</span>```

NOTE: The hast-to-html function is documented here: https://github.com/syntax-tree/hast-util-to-html, maybe some properly set options can fix this.

**Comment by JayaKrishnaNamburu** [comment]
Hey @alexnm just need a small help in writing schema's state value for this above ``v-if`` case 😅

**Comment by alexnm** [comment]
try this one for the tab selector states

```
{
  "type": "state",
  "states": [
    {
      "value": 0,
      "content": {
        "type": "container",
        "children": [{
          "type": "text",
          "children": ["This is the first tab"]
        }]
      }
    },{
      "value": 1,
      "content": {
        "type": "text",
        "children": ["This is the second tab"]
      }
    },{
      "value": {
        "matchingCriteria": "any",
        "conditions": [{
          "operand": 2,
          "operation": "==="
        }]
      },
      "content": {
        "type": "text",
        "children": ["This is the third tab"]
      }
    },{
      "value": {
        "matchingCriteria": "all",
        "conditions": [{
          "operand": 3,
          "operation": ">="
        }, {
          "operand": 5,
          "operation": "<"
        }]
      },
      "content": {
        "type": "text",
        "children": ["This is the fourth tab"]
      }
    }
  ]
}
```

The full example is in `__tests__/fixtures/component-sample.json`

**Comment by JayaKrishnaNamburu** [comment]
The config should be like this 
~~~
const unformatedString = toHTML(htmlObject, {
    allowDangerousHTML: true,
    allowDangerousCharacters: true
  })
~~~

**Comment by alexnm** [comment]
I remember trying this but didn't have time to look into it more.

**Comment by JayaKrishnaNamburu** [comment]
ok, I am following up this. I think the repo needs a fix, I was able to achieve this by making some changes to their repo, will update you once I am done 👍

**Comment by alexnm** [comment]
@JayaKrishnaNamburu please check if there's an option to convert HAST to Vue style templates, because that's why I think this is happening. because `hast-to-html` is expecting the strings to be valid HTML text, not vue-style texts where you have conditions and other stuff

**Comment by JayaKrishnaNamburu** [comment]
Actually i sense there is a small bug at this place in the lib --> https://github.com/syntax-tree/hast-util-to-html/blob/master/lib/element.js#L219 the options are going as null, but when I remove this check all our special characters are rendering fine, somewhere the flag ``allowDangerousCharacters`` is broke i think.

**Comment by JayaKrishnaNamburu** [comment]
Hey @alexnm finally 🚀  here is how we can fix this and I gave a PR for the repo which gives more control over the characters that we can escape, let's wait for them to merge 😄 

Here is the PR --> https://github.com/syntax-tree/hast-util-to-html/pull/12

Once this is merged we can change config to this and get our desired results.
```
const unformatedString = toHTML(htmlObject, {
    allowDangerousCharacters: true,
    allowDangerousHTML: true
    entities: {
      subset: []
    }
  })
```

**Comment by alexnm** [comment]
@JayaKrishnaNamburu awesome work!

**Comment by JayaKrishnaNamburu** [comment]
Thank you
