### ISSUE TITLE
Refactor Project Generators for new master

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [teleporthq/teleport-code-generators#97]
The new master is failing to export projects ``create-react-basic`` && ``create-vue-basic``

**Comment by alexnm** [comment]
it's a typings problem, related to the tsconfig and the changes from #92. working on it.

the generators themselves work if you run the tests `npm run test`, so it's a problem of configuration for the example folder

**Comment by JayaKrishnaNamburu** [comment]
cool @alexnm 👍

**Comment by alexnm** [comment]
@JayaKrishnaNamburu go ahead and pull now, I found this fix for `ts-node` which is used to run the example exporters - https://github.com/TypeStrong/ts-node/issues/628

**Comment by JayaKrishnaNamburu** [comment]
Thanks for the update 👍
